<?php
declare(strict_types=1);

/**
 * tests/_smoke_ai_summary_money_tier.php
 *
 * S-AI-SUMMARY-MONEY-KEY — the AI summary cache never crosses the money
 * boundary.
 *
 * The bug: ai_summaries cached one text per (entity_type, entity_id,
 * summary_type). The context sent to Claude IS redacted per viewer
 * (FleetForgeTools strips amounts unless can_view_financials()), but the cached
 * TEXT was served to anyone — so a summary generated by an admin (balances,
 * revenue) was later read back by a dispatcher (payments:view = none).
 *
 * The fix: ai_summaries.with_money is part of the unique key; SummaryEngine
 * reads/writes only the row for the viewer's tier (moneyTierFor / viewerWithMoney).
 *
 * A — engine, in-process, stubbed sessions (like _smoke_payoff_ai_tools.php),
 *     every write rolled back:
 *       - tier predicates (admin 1, dispatcher 0, system/null user 1);
 *       - generate-as-admin → cacheSummary stamps with_money=1;
 *       - read-as-dispatcher → cachedSummary MISSES (the leak) and generate()
 *         does not return the admin text;
 *       - the dispatcher's own summary lands in a separate with_money=0 row,
 *         regenerating it never overwrites the admin row, each tier reads its own;
 *       - a legacy row written without the column defaults to the money tier
 *         (fail-closed) and is invisible to the dispatcher;
 *       - schema: with_money NOT NULL DEFAULT 1, part of uq_entity_type.
 * B — the REAL api/v1/ai/summary-stream.php, run in a subprocess per REAL user
 *     logged in through auth_login() (54 super_admin, 57 accountant,
 *     56 dispatcher), against an admin-tier row the parent committed:
 *       - financial roles get the cached admin text (cache hit);
 *       - the dispatcher gets NO admin text — the cache misses and the request
 *         falls through to the AI step. ai.enabled is switched off inside the
 *         subprocess's own rolled-back transaction, so a miss ends with
 *         "AI features are not enabled" instead of a paid Claude call.
 *     The committed row is deleted in `finally`.
 *
 * Run:  php tests/_smoke_ai_summary_money_tier.php   Exit 0 pass / 1 fail / 2 setup.
 *
 * @session S-AI-SUMMARY-MONEY-KEY
 */

require_once dirname(__DIR__) . '/config/app.php';
require_once FF_ROOT . '/includes/auth.php';

use FleetForge\AI\SummaryEngine;

$ROOT = dirname(__DIR__);
$pass = 0; $fail = 0; $fails = [];
function ok(string $label, bool $cond, string $detail = ''): void {
    global $pass, $fail, $fails;
    if ($cond) { $pass++; echo "  PASS  {$label}\n"; }
    else { $fail++; echo "  FAIL  {$label}" . ($detail !== '' ? " — {$detail}" : '') . "\n"; $fails[] = $label; }
}

// ── Stub sessions ────────────────────────────────────────────────────────────
// can() reads the SESSION, so these decide can_view_financials() in-process.
// Real active user ids (54 / 56) because ai_summaries.generated_by is an FK.
$adminSess = [
    'id' => 54, 'name' => 'Smoke Admin', 'role_id' => 1, 'role_slug' => 'super_admin',
    'permissions' => [], 'theme' => 'dark',
];
$dispSess = [
    'id' => 56, 'name' => 'Smoke Dispatcher', 'role_slug' => 'dispatcher', 'theme' => 'dark',
    // Dispatcher factory perms that matter here: payments NONE (no money),
    // ai + leases view (can reach a lease summary).
    'permissions' => [
        'payments' => ['view' => false],
        'ai'       => ['view' => true],
        'leases'   => ['view' => true, 'create' => true, 'edit' => true],
    ],
];
$as = static function (array $sess): void { $_SESSION['ff_user'] = $sess; $_SESSION['ff_last_activity'] = time(); };

$ADMIN_TEXT = 'ADMIN SUMMARY — outstanding balance $48,213.07, revenue YTD $912,400.00';
$DISP_TEXT  = 'DISPATCH SUMMARY — unit on rent, return due Friday';

// Sentinel entity ids — never real leases; the cache path never looks them up.
$EID        = 2000000701;   // engine checks (rolled back)
$EID_LEGACY = 2000000702;   // legacy-row check (rolled back)
$EID_E2E    = 2000000703;   // endpoint checks (committed, deleted in finally)

$rowsFor = static fn (int $eid): array => db_select(
    "SELECT with_money, content FROM ai_summaries
      WHERE entity_type='lease' AND entity_id=? AND summary_type='lease_summary'
      ORDER BY with_money", [$eid]);

// ══ A — engine ═══════════════════════════════════════════════════════════════
$pdo = db_pdo();
$pdo->beginTransaction();
try {
    // Hermetic: caching on, AI off (a cache miss in generate() must never bill).
    db_execute("UPDATE settings SET value='1' WHERE `key`='ai.cache_summaries'");
    db_execute("UPDATE settings SET value='0' WHERE `key`='ai.enabled'");
    db_execute("DELETE FROM ai_summaries WHERE entity_type='lease' AND entity_id IN (?, ?)", [$EID, $EID_LEGACY]);

    echo "\n# A1 — schema\n";
    $col = db_row("SHOW COLUMNS FROM ai_summaries WHERE Field='with_money'");
    ok('ai_summaries.with_money exists, NOT NULL DEFAULT 1',
        $col && $col['Null'] === 'NO' && (string) $col['Default'] === '1', json_encode($col));
    $keyCols = array_column(db_select(
        "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.STATISTICS
          WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='ai_summaries' AND INDEX_NAME='uq_entity_type'
          ORDER BY SEQ_IN_INDEX"), 'COLUMN_NAME');
    ok('uq_entity_type = (entity_type, entity_id, summary_type, with_money)',
        $keyCols === ['entity_type', 'entity_id', 'summary_type', 'with_money'], json_encode($keyCols));

    echo "\n# A2 — tier predicates\n";
    $as($adminSess);
    ok('precondition: admin can_view_financials()', can_view_financials());
    ok('admin → viewerWithMoney() true', SummaryEngine::viewerWithMoney() === true);
    $as($dispSess);
    ok('precondition: dispatcher !can_view_financials()', !can_view_financials());
    ok('dispatcher → viewerWithMoney() false', SummaryEngine::viewerWithMoney() === false);
    ok('dispatcher → moneyTierFor(56) false', SummaryEngine::moneyTierFor(56) === false);
    ok('system call (null user, unredacted tools) → moneyTierFor(null) true', SummaryEngine::moneyTierFor(null) === true);

    echo "\n# A3 — generate as admin, read as dispatcher\n";
    $as($adminSess);
    // No explicit tier — the session decides, exactly as generate() would.
    SummaryEngine::cacheSummary('lease', $EID, 'lease_summary', $ADMIN_TEXT, 100, 'claude-sonnet-4-6', 54);
    $rows = $rowsFor($EID);
    ok('admin write stamps with_money=1', count($rows) === 1 && (int) $rows[0]['with_money'] === 1, json_encode($rows));
    $hit = SummaryEngine::cachedSummary('lease', $EID, 'lease_summary');
    ok('admin reads its own cached summary', ($hit['content'] ?? null) === $ADMIN_TEXT, json_encode($hit));
    $gen = SummaryEngine::generate('lease', $EID, 'lease_summary', 54);
    ok('admin generate() serves it from cache', ($gen['cached'] ?? false) === true && ($gen['summary'] ?? '') === $ADMIN_TEXT, json_encode($gen));

    $as($dispSess);
    $miss = SummaryEngine::cachedSummary('lease', $EID, 'lease_summary');
    ok('dispatcher cachedSummary() MISSES the admin row', $miss === null, json_encode($miss));
    $missExplicit = SummaryEngine::cachedSummary('lease', $EID, 'lease_summary', false);
    ok('explicit tier false also misses', $missExplicit === null);
    $genD = SummaryEngine::generate('lease', $EID, 'lease_summary', 56);
    ok('dispatcher generate() does not return the admin text (cache miss → AI step, off here)',
        $genD === null || (($genD['summary'] ?? '') !== $ADMIN_TEXT && ($genD['cached'] ?? false) === false),
        json_encode($genD));

    echo "\n# A4 — each tier keeps its own row\n";
    SummaryEngine::cacheSummary('lease', $EID, 'lease_summary', $DISP_TEXT, 80, 'claude-sonnet-4-6', 56);
    $rows = $rowsFor($EID);
    ok('dispatcher write lands in a separate with_money=0 row (2 rows total)',
        count($rows) === 2 && (int) $rows[0]['with_money'] === 0 && $rows[0]['content'] === $DISP_TEXT
        && (int) $rows[1]['with_money'] === 1 && $rows[1]['content'] === $ADMIN_TEXT, json_encode($rows));
    ok('dispatcher reads its own (redacted-tier) summary',
        (SummaryEngine::cachedSummary('lease', $EID, 'lease_summary')['content'] ?? null) === $DISP_TEXT);
    SummaryEngine::cacheSummary('lease', $EID, 'lease_summary', $DISP_TEXT . ' (regenerated)', 90, 'claude-sonnet-4-6', 56);
    $rows = $rowsFor($EID);
    ok('dispatcher regenerate upserts its own row, admin row untouched',
        count($rows) === 2 && $rows[0]['content'] === $DISP_TEXT . ' (regenerated)' && $rows[1]['content'] === $ADMIN_TEXT,
        json_encode($rows));
    $as($adminSess);
    ok('admin still reads the admin text after the dispatcher wrote',
        (SummaryEngine::cachedSummary('lease', $EID, 'lease_summary')['content'] ?? null) === $ADMIN_TEXT);

    echo "\n# A5 — a row written without the column is money-tier (fail-closed)\n";
    db_execute(
        "INSERT INTO ai_summaries
            (entity_type, entity_id, summary_type, content, tokens_used, model_used,
             generated_at, expires_at, generated_by, is_current)
         VALUES ('lease', ?, 'lease_summary', ?, 10, 'claude-sonnet-4-6', NOW(), DATE_ADD(NOW(), INTERVAL 24 HOUR), NULL, 1)",
        [$EID_LEGACY, $ADMIN_TEXT]
    );
    $legacy = $rowsFor($EID_LEGACY);
    ok('legacy insert defaults with_money=1', count($legacy) === 1 && (int) $legacy[0]['with_money'] === 1, json_encode($legacy));
    $as($dispSess);
    ok('dispatcher never sees a legacy row', SummaryEngine::cachedSummary('lease', $EID_LEGACY, 'lease_summary') === null);
    $as($adminSess);
    ok('admin still reads a legacy row', (SummaryEngine::cachedSummary('lease', $EID_LEGACY, 'lease_summary')['content'] ?? null) === $ADMIN_TEXT);
} finally {
    $pdo->rollBack();
    echo "\n(A rolled back — DB + settings unchanged)\n";
}

// ══ B — the real summary-stream.php, real logins ═════════════════════════════
// Subprocess harness: one process = one request. It opens a transaction FIRST
// (so login side effects, the rate-limit row and the ai.enabled switch all roll
// back when the process exits), logs a real user in via auth_login(), feeds the
// POST body through a php:// stream wrapper, then requires the endpoint.
$PID = getmypid();
$harnessFile = sys_get_temp_dir() . '/_ff_ai_summary_tier_' . $PID . '.php';
file_put_contents($harnessFile, <<<PHP
<?php
if (PHP_SAPI !== 'cli') { http_response_code(403); exit('cli only'); }
error_reporting(E_ERROR | E_PARSE);
\$uid = (int) (\$argv[1] ?? 0);
\$payload = base64_decode(\$argv[2] ?? '');
\$_SERVER['REQUEST_METHOD'] = 'POST'; \$_SERVER['CONTENT_TYPE'] = 'application/json';
\$_SERVER['HTTP_X_CSRF_TOKEN'] = 'smoketoken'; \$_SERVER['REMOTE_ADDR'] = '127.0.0.1';
\$_SERVER['HTTP_HOST'] = 'localhost'; \$_SERVER['HTTP_USER_AGENT'] = 'FleetForge-AiTier-Smoke/1.0';
require '{$ROOT}/config/app.php';
require_once FF_ROOT . '/includes/auth.php';
db_pdo()->beginTransaction();   // never committed — the process exit rolls it all back
db_execute("UPDATE settings SET value='1' WHERE `key`='ai.cache_summaries'");
db_execute("UPDATE settings SET value='0' WHERE `key`='ai.enabled'");   // a miss must not bill Claude
@session_start();
\$u = db_row("SELECT u.*, r.slug AS role_slug FROM users u JOIN user_roles r ON r.id = u.role_id WHERE u.id = ?", [\$uid]);
if (!\$u) { echo "FFSMOKE-FIN=missing-user\n"; exit; }
@auth_login(\$u);
\$_SESSION['csrf_token'] = 'smoketoken';
echo 'FFSMOKE-FIN=' . (can_view_financials() ? '1' : '0') . "\n";
class FfAiTierIn {
    public \$context;
    private static string \$buf = '';
    private int \$pos = 0;
    public static function set(string \$s): void { self::\$buf = \$s; }
    public function stream_open(\$p, \$m, \$o, &\$opened): bool { \$this->pos = 0; return true; }
    public function stream_read(\$c) { \$ch = substr(self::\$buf, \$this->pos, \$c); \$this->pos += strlen(\$ch); return \$ch; }
    public function stream_eof(): bool { return \$this->pos >= strlen(self::\$buf); }
    public function stream_stat(): array { return []; }
    public function stream_seek(\$o, \$w): bool { \$this->pos = \$o; return true; }
    public function stream_tell(): int { return \$this->pos; }
}
FfAiTierIn::set(\$payload);
stream_wrapper_unregister('php'); stream_wrapper_register('php', 'FfAiTierIn');
require '{$ROOT}/api/v1/ai/summary-stream.php';
PHP);

/** Run summary-stream.php as a real user → [fin flag, decoded SSE events, raw]. */
$streamAs = static function (int $uid, array $body) use ($harnessFile): array {
    $out = (string) shell_exec(escapeshellarg(PHP_BINARY) . ' ' . escapeshellarg($harnessFile)
        . ' ' . escapeshellarg((string) $uid) . ' ' . escapeshellarg(base64_encode(json_encode($body))) . ' 2>/dev/null');
    $fin = preg_match('/^FFSMOKE-FIN=(\S+)/m', $out, $m) ? $m[1] : 'none';
    $events = [];
    foreach (preg_split('/\R/', $out) as $line) {
        if (str_starts_with($line, 'data: ')) {
            $e = json_decode(substr($line, 6), true);
            if (is_array($e)) $events[] = $e;
        }
    }
    return ['fin' => $fin, 'events' => $events, 'raw' => substr($out, 0, 300)];
};
$textOf = static fn (array $events): string => implode('', array_map(
    static fn ($e) => ($e['t'] ?? '') === 'tok' ? (string) ($e['c'] ?? '') : '', $events));
$errOf  = static function (array $events): ?string {
    foreach ($events as $e) { if (($e['t'] ?? '') === 'err') return (string) ($e['m'] ?? ''); }
    return null;
};
$cachedDone = static function (array $events): bool {
    foreach ($events as $e) { if (($e['t'] ?? '') === 'done' && !empty($e['cached'])) return true; }
    return false;
};

try {
    echo "\n# B — real summary-stream.php, admin-generated row, real logins\n";
    // Generate as admin through the real write path (session-derived tier) and
    // COMMIT it — each subprocess has its own connection.
    db_execute("DELETE FROM ai_summaries WHERE entity_type='lease' AND entity_id=?", [$EID_E2E]);
    $as($adminSess);
    SummaryEngine::cacheSummary('lease', $EID_E2E, 'lease_summary', $ADMIN_TEXT, 100, 'claude-sonnet-4-6', 54);
    $seed = $rowsFor($EID_E2E);
    ok('setup: admin-generated row committed with with_money=1',
        count($seed) === 1 && (int) $seed[0]['with_money'] === 1, json_encode($seed));

    $body = ['entity_type' => 'lease', 'entity_id' => $EID_E2E, 'summary_type' => 'lease_summary', 'force' => 0];

    $a = $streamAs(54, $body);
    ok('super_admin (54) logged in with financials', $a['fin'] === '1', $a['raw']);
    ok('super_admin gets the cached admin summary', $textOf($a['events']) === $ADMIN_TEXT && $cachedDone($a['events']),
        json_encode($a['events']));

    $c = $streamAs(57, $body);
    ok('accountant (57) logged in with financials', $c['fin'] === '1', $c['raw']);
    ok('accountant gets the cached admin summary', $textOf($c['events']) === $ADMIN_TEXT && $cachedDone($c['events']),
        json_encode($c['events']));

    $d = $streamAs(56, $body);
    ok('dispatcher (56) logged in WITHOUT financials', $d['fin'] === '0', $d['raw']);
    ok('dispatcher receives NO admin text from the cache',
        !str_contains($textOf($d['events']), '48,213.07') && !$cachedDone($d['events']), json_encode($d['events']));
    ok('dispatcher request fell through to the AI step (cache miss, AI off here)',
        str_contains((string) $errOf($d['events']), 'AI features are not enabled'), json_encode($d['events']));

    $after = $rowsFor($EID_E2E);
    ok('endpoint runs left the admin row untouched and wrote nothing',
        count($after) === 1 && $after[0]['content'] === $ADMIN_TEXT, json_encode($after));
} finally {
    db_execute("DELETE FROM ai_summaries WHERE entity_type='lease' AND entity_id=?", [$EID_E2E]);
    @unlink($harnessFile);
    echo "\n(B cleaned up — sentinel row deleted)\n";
}

echo "\n" . str_repeat('─', 60) . "\n";
echo "RESULT: {$pass} passed, {$fail} failed\n";
if ($fail) { echo "FAILURES: " . implode('; ', $fails) . "\n"; }
exit($fail ? 1 : 0);
