-- ════════════════════════════════════════════════════════════════════════════
-- S-AI-SUMMARY-MONEY-KEY — the AI summary cache is keyed by money visibility.
--
-- ai_summaries cached ONE text per (entity_type, entity_id, summary_type). The
-- context fed to Claude IS redacted per viewer (FleetForgeTools strips money
-- unless can_view_financials()), but the cached TEXT was then served to any
-- viewer — so a summary generated by an admin/accountant (amounts, balances,
-- revenue) was later read back by a dispatcher (payments:view = none).
--
-- Fix: a `with_money` flag on every row, part of the unique key. SummaryEngine
-- reads and writes only the row matching the viewer's can_view_financials(), so
-- the two audiences never share cached text.
--
-- DEFAULT 1 is the fail-closed choice:
--   * existing rows were generated by an unknown viewer — tagging them 1 means
--     they are only ever served to financial viewers (a money-free text shown
--     to an accountant is harmless; the reverse is the leak being closed);
--   * any writer that forgets the column also lands in the financial tier.
--
-- Steps INFORMATION_SCHEMA-guarded → idempotent (re-runnable).
-- ════════════════════════════════════════════════════════════════════════════

SET @schema = DATABASE();

-- ── 1. ai_summaries.with_money ──────────────────────────────────────────────
SET @col = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA=@schema AND TABLE_NAME='ai_summaries' AND COLUMN_NAME='with_money');
SET @stmt = IF(@col=0,
    "ALTER TABLE ai_summaries ADD COLUMN `with_money` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'S-AI-SUMMARY-MONEY-KEY: 1 = generated for a can_view_financials() viewer (may contain amounts); 0 = money-redacted context. Part of the cache key - never serve a 1 row to a 0 viewer.' AFTER `summary_type`",
    "SELECT 'ai_summaries.with_money exists' AS info");
PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;

-- ── 2. UNIQUE(entity_type, entity_id, summary_type) → + with_money ──────────
-- cacheSummary() upserts on this key; without with_money in it a dispatcher's
-- regenerate would overwrite the admin's row (and vice versa) instead of each
-- audience keeping its own. Guard on the key's column count so it runs once.
SET @keycols = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
    WHERE TABLE_SCHEMA=@schema AND TABLE_NAME='ai_summaries' AND INDEX_NAME='uq_entity_type');
SET @stmt = IF(@keycols<>4,
    "ALTER TABLE ai_summaries DROP INDEX `uq_entity_type`, ADD UNIQUE KEY `uq_entity_type` (`entity_type`,`entity_id`,`summary_type`,`with_money`)",
    "SELECT 'uq_entity_type already includes with_money' AS info");
PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
