<?php
declare(strict_types=1);

/**
 * api/v1/storage/serve.php
 *
 * Local file serve endpoint for the local STORAGE_DRIVER.
 * In production (STORAGE_DRIVER=s3), this endpoint is never called —
 * S3 presigned URLs go directly to AWS.
 *
 * URL shape (generated by StorageClient::urlLocal()):
 *   /fleetforge/api/v1/storage/serve?key=equipment/14/cvi_...pdf&exp=1234567890&sig=abc123
 *
 * Security:
 *   - Requires valid session (require_auth_api) — prevents unauthenticated
 *     enumeration of stored files.
 *   - HMAC-SHA256 signature validated against APP_SECRET + expiry time.
 *   - Expiry enforced — URLs become invalid after $expiry seconds.
 *   - key validated by StorageClient::validateStoragePath() (no ../ traversal).
 *   - File must physically exist inside FF_ROOT/storage/.
 *
 * @method  GET
 * @auth    Session required; any authenticated staff member may read documents
 * @params  key (string), exp (int unix timestamp), sig (sha256 hex)
 * @returns File bytes with correct Content-Type and Content-Disposition: inline
 *          404 NOT_FOUND if file missing
 *          403 FORBIDDEN if HMAC invalid or expired
 *
 * Decisions: D7 (routing), D9 (storage abstraction), Trap 7 (never expose paths)
 * Session: S020 addendum
 */

require_once dirname(__DIR__, 3) . '/api/bootstrap.php';
require_once FF_ROOT . '/vendor/autoload.php';

use FleetForge\Storage\StorageClient;

require_method('GET');
require_auth_api();

// -----------------------------------------------------------------------
// 1. Read + sanitise query params
// -----------------------------------------------------------------------
$key = $_GET['key'] ?? '';
$exp = (int)($_GET['exp'] ?? 0);
$sig = $_GET['sig'] ?? '';

if ($key === '' || $exp === 0 || $sig === '') {
    json_error('MISSING_REQUIRED', 'key, exp and sig are required.', 422);
}

// -----------------------------------------------------------------------
// 2. Validate HMAC signature + expiry via StorageClient
// -----------------------------------------------------------------------
// Returns null if invalid or expired — we return 403 without revealing why
$validKey = StorageClient::verifyLocalUrl($key, $exp, $sig);
if ($validKey === null) {
    json_error('FORBIDDEN', 'File URL is invalid or has expired. Reload the page to get a fresh link.', 403);
}

// -----------------------------------------------------------------------
// 3. Resolve and validate the absolute filesystem path
// -----------------------------------------------------------------------
// localPath() prepends FF_ROOT/storage/ and re-validates the key.
// This prevents directory traversal even if verifyLocalUrl somehow passed.
$absPath = StorageClient::localPath($validKey);

if (!file_exists($absPath) || !is_file($absPath)) {
    json_error('NOT_FOUND', 'File not found.', 404);
}

// -----------------------------------------------------------------------
// 4. Detect MIME type from file content (never trust client or extension)
// -----------------------------------------------------------------------
$finfo    = finfo_open(FILEINFO_MIME_TYPE);
$mimeType = finfo_file($finfo, $absPath);
finfo_close($finfo);

// Restrict to types we actually store — block unexpected binary types
$allowedMimes = [
    'application/pdf',
    'image/jpeg',
    'image/png',
    'image/gif',
    'image/webp',
];
if (!in_array($mimeType, $allowedMimes, true)) {
    // Serve as octet-stream rather than refusing — the file exists and auth passed
    $mimeType = 'application/octet-stream';
}

// -----------------------------------------------------------------------
// 5. Build a safe download filename from the storage key (last segment)
// -----------------------------------------------------------------------
$safeName = basename($validKey);
// Strip any remaining non-printable characters from the filename
$safeName = preg_replace('/[^\x20-\x7E]/', '', $safeName);
if ($safeName === '' || $safeName === '.') {
    $safeName = 'document';
}

// -----------------------------------------------------------------------
// 6. Serve the file — inline for PDFs and images (opens in browser tab)
// -----------------------------------------------------------------------
$disposition = in_array($mimeType, ['application/pdf', 'image/jpeg', 'image/png', 'image/gif', 'image/webp'], true)
    ? 'inline'
    : 'attachment';

header('Content-Type: ' . $mimeType);
header('Content-Disposition: ' . $disposition . '; filename="' . $safeName . '"');
header('Content-Length: ' . filesize($absPath));
header('Cache-Control: private, max-age=300');   // 5-min browser cache — URL is short-lived anyway
header('X-Content-Type-Options: nosniff');

readfile($absPath);
exit;
