<?php
declare(strict_types=1);

/**
 * app/legal/terms.php — Terms of Service (public route /legal/terms)
 *
 * Session: S-LEGAL-FOOTER-COMMERCIAL (2026-05-17)
 */

require_once realpath(dirname(__DIR__, 2) . '/config/app.php');

$pageTitle = 'Terms of Service';
require FF_ROOT . '/includes/legal_header.php';
?>

<div class="legal-hero">
    <h1>Terms of Service</h1>
    <p>Effective: January 1, 2026 &nbsp;·&nbsp; Last updated: May 17, 2026 &nbsp;·&nbsp; Governing law: British Columbia, Canada</p>
</div>

<div class="legal-highlight">
    Please read these Terms carefully before using FleetForge. By accessing or using the software, you agree to be bound by these Terms. If you do not agree, do not use the software.
</div>

<div class="legal-toc">
    <h3>Contents</h3>
    <ol>
        <li><a href="#definitions">Definitions</a></li>
        <li><a href="#license">License Grant</a></li>
        <li><a href="#accounts">Accounts &amp; Access</a></li>
        <li><a href="#payment">Payment &amp; Billing</a></li>
        <li><a href="#data">Data Ownership &amp; Portability</a></li>
        <li><a href="#ip">Intellectual Property</a></li>
        <li><a href="#confidentiality">Confidentiality</a></li>
        <li><a href="#sla">Service Level &amp; Uptime</a></li>
        <li><a href="#warranties">Warranties &amp; Disclaimers</a></li>
        <li><a href="#liability">Limitation of Liability</a></li>
        <li><a href="#indemnification">Indemnification</a></li>
        <li><a href="#termination">Termination</a></li>
        <li><a href="#governing">Governing Law &amp; Disputes</a></li>
        <li><a href="#changes">Changes to These Terms</a></li>
        <li><a href="#contact">Contact</a></li>
    </ol>
</div>

<div class="legal-section" id="definitions">
    <h2>1. Definitions</h2>
    <p><strong>"Avi Technologies"</strong> (also "we," "us," "our") means Avi Technologies Inc., a company incorporated under the laws of British Columbia, Canada.</p>
    <p><strong>"FleetForge"</strong> means the fleet management software platform, including all web interfaces, APIs, mobile applications, and associated documentation made available by Avi Technologies.</p>
    <p><strong>"Client"</strong> (also "you," "your") means the company or organization that has purchased a license to use FleetForge and all authorized users within that organization.</p>
    <p><strong>"Authorized Users"</strong> means the individual employees, contractors, or agents of the Client who are permitted to access FleetForge under the Client's account.</p>
    <p><strong>"Client Data"</strong> means all data, content, and information submitted, uploaded, or generated by the Client and its Authorized Users through FleetForge, including but not limited to customer records, fleet records, lease agreements, invoices, GPS telematics data, inspection records, and financial data.</p>
    <p><strong>"Subscription"</strong> means the paid license to access and use FleetForge for the term and scope agreed upon in the applicable order form or agreement.</p>
</div>

<div class="legal-section" id="license">
    <h2>2. License Grant</h2>
    <p>Subject to your compliance with these Terms and payment of applicable fees, Avi Technologies grants you a limited, non-exclusive, non-transferable, non-sublicensable license to access and use FleetForge solely for your internal business operations during the Subscription term.</p>
    <h3>2.1 Restrictions</h3>
    <p>You may not, and may not permit others to:</p>
    <ul>
        <li>Copy, modify, translate, or create derivative works of FleetForge</li>
        <li>Reverse engineer, decompile, disassemble, or otherwise attempt to discover the source code or underlying algorithms of FleetForge</li>
        <li>Sell, resell, rent, lease, transfer, assign, or sublicense FleetForge to any third party</li>
        <li>Remove or obscure any proprietary notices, labels, or marks on FleetForge</li>
        <li>Use FleetForge to build a competing product or service</li>
        <li>Use FleetForge in any way that violates applicable laws or these Terms</li>
        <li>Exceed the number of Authorized Users specified in your Subscription</li>
    </ul>
    <h3>2.2 White-Label Rights</h3>
    <p>Clients who have purchased a white-label license may configure FleetForge to display their own company name and logo within the software. This does not grant any rights to the FleetForge source code or intellectual property.</p>
</div>

<div class="legal-section" id="accounts">
    <h2>3. Accounts &amp; Access</h2>
    <p>You are responsible for maintaining the confidentiality of all login credentials associated with your FleetForge account. You agree to notify Avi Technologies immediately at <a href="mailto:security@avitechnologies.ca">security@avitechnologies.ca</a> upon becoming aware of any unauthorized access to your account.</p>
    <p>You are responsible for all activity that occurs under your account, including actions taken by your Authorized Users. Avi Technologies is not liable for any loss or damage arising from your failure to maintain the security of your credentials.</p>
    <p>Each Authorized User must be an individual (not a shared or generic login). You may not share login credentials between multiple individuals.</p>
</div>

<div class="legal-section" id="payment">
    <h2>4. Payment &amp; Billing</h2>
    <p>Subscription fees are invoiced according to the pricing and payment schedule agreed upon in your order form or service agreement. All fees are quoted in Canadian dollars unless otherwise specified.</p>
    <p>Invoices are due within the payment terms specified in your agreement. Overdue amounts may be subject to a late payment fee of 2% per month (24% per annum) compounded monthly, or the maximum rate permitted by law, whichever is less.</p>
    <p>All fees are exclusive of applicable taxes, including GST, PST, HST, or other taxes as required by law. You are responsible for all taxes applicable to your Subscription.</p>
    <h3>4.1 Suspension for Non-Payment</h3>
    <p>Avi Technologies reserves the right to suspend access to FleetForge for accounts that are more than 30 days past due, upon reasonable written notice. Suspension does not relieve you of the obligation to pay outstanding amounts.</p>
    <h3>4.2 Refunds</h3>
    <p>Subscription fees are non-refundable except as required by applicable law or as expressly stated in your service agreement. If you cancel your Subscription mid-term, you retain access until the end of the current billing period.</p>
</div>

<div class="legal-section" id="data">
    <h2>5. Data Ownership &amp; Portability</h2>
    <p><strong>You own your data.</strong> All Client Data remains your exclusive property. Avi Technologies does not claim any ownership rights in Client Data.</p>
    <p>Avi Technologies processes Client Data solely to provide the FleetForge service and as described in our <a href="<?= e(legal_url('privacy')) ?>">Privacy Policy</a> and <a href="<?= e(legal_url('dpa')) ?>">Data Processing Agreement</a>.</p>
    <h3>5.1 Data Export</h3>
    <p>You may export your Client Data at any time using the export features within FleetForge. Upon written request following termination of your Subscription, Avi Technologies will provide a complete export of your Client Data in a machine-readable format within 30 days, at no charge.</p>
    <h3>5.2 Data Deletion</h3>
    <p>Following termination of your Subscription and completion of any data export period, Avi Technologies will delete or anonymize your Client Data within 90 days, unless retention is required by applicable law.</p>
    <h3>5.3 GPS &amp; Telematics Data</h3>
    <p>FleetForge may integrate with third-party GPS and telematics providers (such as Samsara) at your direction. Data obtained from such integrations is Client Data. Avi Technologies does not independently transmit telematics data to third parties without your authorization. You are responsible for ensuring your use of telematics data complies with applicable privacy laws and any obligations to your drivers or employees.</p>
</div>

<div class="legal-section" id="ip">
    <h2>6. Intellectual Property</h2>
    <p>FleetForge, including all software, algorithms, user interfaces, documentation, and associated materials, is the exclusive property of Avi Technologies and is protected by Canadian and international intellectual property laws.</p>
    <p>These Terms do not grant you any rights in FleetForge except the limited license expressly set out in Section 2. All rights not expressly granted are reserved by Avi Technologies.</p>
    <p>If you submit feedback, suggestions, or ideas about FleetForge, you grant Avi Technologies a perpetual, irrevocable, royalty-free license to use that feedback for any purpose without compensation to you.</p>
</div>

<div class="legal-section" id="confidentiality">
    <h2>7. Confidentiality</h2>
    <p>Each party may receive confidential information from the other in connection with FleetForge. "Confidential Information" means any information that is marked confidential or that a reasonable person would understand to be confidential given the context of disclosure.</p>
    <p>Each party agrees to: (a) hold the other's Confidential Information in strict confidence using at least the same care it uses to protect its own confidential information, but no less than reasonable care; (b) not disclose Confidential Information to any third party without prior written consent; and (c) use Confidential Information only as necessary to exercise rights or perform obligations under these Terms.</p>
    <p>Confidentiality obligations do not apply to information that: (a) is or becomes publicly known through no breach of these Terms; (b) is rightfully received from a third party without restriction; (c) is independently developed without use of Confidential Information; or (d) is required to be disclosed by law or court order, provided the receiving party gives prompt written notice where permitted.</p>
</div>

<div class="legal-section" id="sla">
    <h2>8. Service Level &amp; Uptime</h2>
    <p>Avi Technologies will use commercially reasonable efforts to make FleetForge available 99.5% of the time in any given calendar month, excluding scheduled maintenance windows and circumstances beyond our reasonable control.</p>
    <p>Scheduled maintenance will be communicated at least 48 hours in advance where possible and performed during off-peak hours (between 11:00 PM and 5:00 AM Pacific Time).</p>
    <p>Avi Technologies does not guarantee that FleetForge will be error-free or uninterrupted. Your sole remedy for downtime exceeding the uptime commitment is a service credit as specified in your service agreement.</p>
</div>

<div class="legal-section" id="warranties">
    <h2>9. Warranties &amp; Disclaimers</h2>
    <p>Avi Technologies warrants that FleetForge will perform materially in accordance with its documentation under normal use. If FleetForge fails to meet this warranty, your exclusive remedy is for Avi Technologies to use commercially reasonable efforts to correct the non-conformity.</p>
    <p><strong>EXCEPT AS EXPRESSLY SET OUT IN THESE TERMS, FLEETFORGE IS PROVIDED "AS IS." AVI TECHNOLOGIES DISCLAIMS ALL OTHER WARRANTIES, EXPRESS OR IMPLIED, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. AVI TECHNOLOGIES DOES NOT WARRANT THAT FLEETFORGE WILL MEET YOUR REQUIREMENTS OR THAT ITS OPERATION WILL BE UNINTERRUPTED OR ERROR-FREE.</strong></p>
</div>

<div class="legal-section" id="liability">
    <h2>10. Limitation of Liability</h2>
    <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL AVI TECHNOLOGIES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, REVENUE, DATA, BUSINESS, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR YOUR USE OF FLEETFORGE, EVEN IF AVI TECHNOLOGIES HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
    <p>AVI TECHNOLOGIES' TOTAL CUMULATIVE LIABILITY ARISING OUT OF OR IN CONNECTION WITH THESE TERMS WILL NOT EXCEED THE FEES PAID BY YOU TO AVI TECHNOLOGIES IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM.</p>
    <p>The limitations in this section apply regardless of the form of action, whether in contract, tort (including negligence), strict liability, or otherwise, and even if any limited remedy fails of its essential purpose.</p>
</div>

<div class="legal-section" id="indemnification">
    <h2>11. Indemnification</h2>
    <p>You agree to indemnify, defend, and hold harmless Avi Technologies and its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable legal fees) arising out of or relating to:</p>
    <ul>
        <li>Your use of FleetForge in violation of these Terms</li>
        <li>Your Client Data, including any claim that Client Data infringes any third-party intellectual property or privacy rights</li>
        <li>Your violation of any applicable law or regulation</li>
        <li>Your telematics data collection practices and obligations to drivers or employees</li>
    </ul>
    <p>Avi Technologies will indemnify you against third-party claims that FleetForge itself (excluding Client Data) infringes any Canadian patent, copyright, or trademark, provided you give Avi Technologies prompt written notice and reasonable cooperation in the defense.</p>
</div>

<div class="legal-section" id="termination">
    <h2>12. Termination</h2>
    <p>Either party may terminate these Terms upon written notice if the other party materially breaches these Terms and fails to cure the breach within 30 days of written notice.</p>
    <p>Avi Technologies may terminate or suspend your access immediately upon notice if you: (a) violate Section 2 (License Restrictions); (b) fail to pay undisputed amounts within 60 days of the due date; or (c) become insolvent or subject to insolvency proceedings.</p>
    <p>Upon termination, your license to use FleetForge ends immediately. Sections 5, 6, 7, 9, 10, 11, and 13 survive termination.</p>
</div>

<div class="legal-section" id="governing">
    <h2>13. Governing Law &amp; Disputes</h2>
    <p>These Terms are governed by and construed in accordance with the laws of the Province of British Columbia and the federal laws of Canada applicable therein, without regard to conflict of law principles.</p>
    <p>The parties agree to first attempt to resolve any dispute through good-faith negotiation. If a dispute cannot be resolved within 30 days, either party may initiate binding arbitration under the rules of the BC International Commercial Arbitration Centre (BCICAC), with proceedings conducted in English in Surrey, British Columbia.</p>
    <p>Notwithstanding the foregoing, either party may seek injunctive or equitable relief in any court of competent jurisdiction to prevent irreparable harm pending resolution of a dispute.</p>
</div>

<div class="legal-section" id="changes">
    <h2>14. Changes to These Terms</h2>
    <p>Avi Technologies may update these Terms from time to time. We will notify you of material changes by email to the address associated with your account at least 30 days before the changes take effect. Your continued use of FleetForge after the effective date constitutes acceptance of the updated Terms.</p>
    <p>If you object to any changes, you may terminate your Subscription before the effective date by providing written notice to <a href="mailto:legal@avitechnologies.ca">legal@avitechnologies.ca</a>.</p>
</div>

<div class="legal-section" id="contact">
    <h2>15. Contact</h2>
    <p>For legal inquiries: <a href="mailto:legal@avitechnologies.ca">legal@avitechnologies.ca</a></p>
    <p>For privacy inquiries: <a href="mailto:privacy@avitechnologies.ca">privacy@avitechnologies.ca</a></p>
    <p>For support: <a href="mailto:support@avitechnologies.ca">support@avitechnologies.ca</a></p>
    <p>Avi Technologies Inc.<br>Surrey, British Columbia, Canada</p>
</div>

<?php require FF_ROOT . '/includes/legal_footer.php'; ?>
