<?php
declare(strict_types=1);

/**
 * api/v1/admin/intelligence/test_briefing.php
 *
 * Operator's "Send me a test briefing now" button (Intelligence
 * settings tab → Morning Briefing section).
 *
 * Behavior (D-INTEL-3):
 *   - Reads the CACHED brief from report_cache (NOT a fresh Claude
 *     API call). Avoids accidentally burning AI tokens from a settings
 *     page button. If no cache exists (cron hasn't run today, or
 *     ai.briefing_enabled=0 so generation was skipped), returns 422
 *     with a clear message.
 *   - Renders via MorningBriefingRenderer::renderBody() — identical to
 *     what the production morning email would look like for the
 *     current user.
 *   - Sends via Mailer::send to the CURRENT USER's email only. Never
 *     sends to other recipients (no "test the entire dispatch" mode —
 *     that would require explicit additional gating + bulk-send risk
 *     review).
 *   - Logs a notification_log entry with notification_type='morning_digest_test'
 *     (distinct from the daily 'morning_digest' so it doesn't trigger
 *     the cron's 23-hour dedup).
 *
 * @method  POST
 * @auth    require_permission('settings', 'edit') — same gate as
 *          modifying AI/briefing settings; if you can change the
 *          settings, you can test-send.
 * @returns 200 { success: true, recipient, subject, sent_at }
 *          422 if no cache available or ai.briefing_enabled=0
 *
 * @session  S-INTEL-TAB
 * @decision D-INTEL-3 (cached-only test-send; no live Claude API call)
 */

require_once dirname(__DIR__, 4) . '/api/bootstrap.php';

require_method('POST');
require_auth_api();
require_permission('settings', 'edit');

use FleetForge\Notifications\MorningBriefingRenderer;
use FleetForge\Notifications\Mailer;
use FleetForge\Email\EmailService;

try {
    // ── Gate: briefing enabled. ─────────────────────────────
    if ((string) settings_get('ai.briefing_enabled', '1') !== '1') {
        json_error(
            'BRIEFING_DISABLED',
            'Morning briefing is disabled (ai.briefing_enabled=0). Toggle it on in the Intelligence settings tab before sending a test.',
            422
        );
    }

    // ── Gate: cache exists per D-INTEL-3. ───────────────────
    if (!MorningBriefingRenderer::hasCachedBrief()) {
        json_error(
            'NO_CACHED_BRIEFING',
            'No cached briefing available. The morning brief is generated by cron/ai_fleet_brief.php at 04:00 daily. Wait for the next run or check that ai.enabled and ai.briefing_enabled are both set to 1.',
            422
        );
    }

    $user = current_user();
    if (!$user || empty($user['email'])) {
        json_error('NO_EMAIL', 'Your account has no email address configured. Add an email before sending a test.', 422);
    }
    $userId = (int) $user['id'];
    $email  = (string) $user['email'];
    $name   = (string) ($user['name'] ?? 'Team');

    if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        json_error('INVALID_EMAIL', 'Your account email is not a valid address: ' . $email, 422);
    }

    // ── Render + send. ──────────────────────────────────────
    $payload     = MorningBriefingRenderer::buildPayload();
    $bodyHtml    = MorningBriefingRenderer::renderBody($name, $payload);
    $wrappedHtml = EmailService::renderEmailHtml($bodyHtml);
    $subject     = '[TEST] Morning Briefing — ' . date('M j, Y');

    $ok = Mailer::send(
        toEmail:  $email,
        toName:   $name,
        subject:  $subject,
        htmlBody: $wrappedHtml,
    );

    // Log distinctly from the daily morning_digest so the cron's 23h
    // dedup doesn't suppress tomorrow's real send.
    db_insert('notification_log', [
        'rule_id'           => null,
        'channel'           => 'email',
        'recipient'         => $email,
        'subject'           => $subject,
        'body'              => mb_substr(strip_tags($bodyHtml), 0, 2000),
        'entity_type'       => 'user',
        'entity_id'         => $userId,
        'notification_type' => 'morning_digest_test',
        'status'            => $ok ? 'sent' : 'failed',
        'error_message'     => $ok ? null : 'Mailer::send returned false',
        'sent_at'           => $ok ? date('Y-m-d H:i:s') : null,
    ]);

    db_insert('audit_log', [
        'user_id'      => $userId,
        'user_name'    => $name,
        'action'       => 'create',
        'module'       => 'settings',
        'entity_type'  => 'morning_briefing_test',
        'entity_id'    => $userId,
        'entity_label' => 'Test briefing → ' . $email,
        'notes'        => $ok ? 'Test briefing sent successfully.' : 'Test briefing failed to send.',
        'ip_address'   => $_SERVER['REMOTE_ADDR'] ?? null,
    ]);

    if (!$ok) {
        json_error('SEND_FAILED', 'Mailer reported failure. Check email/SMTP settings in the Integrations tab.', 502);
    }

    json_success([
        'recipient' => $email,
        'subject'   => $subject,
        'sent_at'   => date('Y-m-d H:i:s'),
    ]);

} catch (\Throwable $e) {
    json_error('INTERNAL_ERROR', 'Test briefing failed: ' . $e->getMessage(), 500);
}
