<?php
/**
 * FleetForge — Dress-Rehearsal Seed  (S-DRESS-REHEARSAL-WIPE-AND-SEED)
 *
 * Repopulates a freshly-wiped DEV database with a small, coherent,
 * production-shaped dataset for the 2026-06 dress rehearsal. Run AFTER
 * scripts/demo_wipe.php has cleared the customer/billing/accounting tables.
 *
 * WHAT THIS CREATES (per docs/FLEETFORGE_DRESS_REHEARSAL_PLAN_2026-06.md,
 * operator decisions SD1=(b) realistic BC trucking customers, SD2=(b) fresh
 * focused equipment set):
 *   - 6  equipment_templates  (one rate card per heavy-trailer / tractor type)
 *   - 25 equipment_units      (8 dry van, 5 reefer, 4 flatbed, 3 step deck,
 *                              3 day-cab tractor, 2 sleeper tractor)
 *   - 12 customers            (BC trucking companies, all province=BC)
 *   - 4  vendors              (maintenance / parts / fuel / equipment finance)
 *   - 6  leases               (varied lifecycle: just-started, mid-cycle
 *                              partial, mid-cycle current, ending-soon,
 *                              long-term, recently-closed)
 *   - ~14 invoices            (generated by InvoiceGenerator, then SENT)
 *   - 4  payments             (against leases 2/3/5/6; cheque / EFT / e-transfer)
 *   - 3  bills                (maintenance / parts / fuel — AP, awaiting payment)
 *
 * DESIGN DECISIONS
 *   D-REHEARSAL-SEED-DEDICATED — this is a NEW script, NOT a modification of
 *     scripts/demo_seed.php. demo_seed.php (the existing dev presentation seed)
 *     is left untouched. Helper patterns (daysAgo/daysFromNow, freezeTax,
 *     buildEquipSnap, the lease insert block, InvoiceGenerator usage, the
 *     Path-B counter recompute) are BORROWED from demo_seed.php.
 *
 *   Operational-layer only — NO general-ledger backfill. InvoiceGenerator
 *     does not post a JE for regular invoices (only credit notes), and we
 *     SEND invoices via a direct UPDATE rather than the send API, so no
 *     AutoEntryBridge JE fires. Bills are likewise created WITHOUT journal
 *     entries (journal_entry_id stays NULL). The entire dataset therefore
 *     models the customer / billing / AP operational layer with no acc_*
 *     journal posting — internally consistent (the GL-backfill equivalent of
 *     scripts/demo_accounting.php is deliberately out of scope; QBO sync is
 *     deferred to S-DRESS-REHEARSAL-SYNC part 2).
 *
 *   Idempotent — Step 0 clears (TRUNCATE) every table this seed writes, then
 *     reseeds, so a second run produces the same logical state. All generated
 *     identifiers (unit numbers, VINs, contract numbers, invoice numbers via a
 *     reset counter) are DETERMINISTIC (index-derived, no random_*), so re-runs
 *     are reproducible.
 *
 *   Fail-closed on production — re-asserts APP_ENV != 'production' at the top
 *     (config/app.php defaults APP_ENV to 'production' when unset, so an
 *     ambiguous/missing env ALSO refuses). Mirrors demo_wipe.php's Layer-1
 *     guard. The equipment TRUNCATE in Step 0 sits behind this same gate.
 *
 *   bcmath for money (D16) — all monetary arithmetic (bill taxes, payment
 *     aggregation) uses bc* functions; floats are never used for currency.
 *
 *   Inclusive day counting (D14) — billing periods are expressed as
 *     [start, end] inclusive; InvoiceGenerator computes days = diff + 1.
 *
 * NOTE on country: customers.country is set to 'Canada' (the customers table
 * default + scripts/demo_seed.php convention + the value QBO customer-sync has
 * been exercised against), NOT the literal 'CA' from the session prompt. The
 * province code stays 'BC'. This avoids a FF↔QBO country-mapping mismatch in
 * part 2.
 *
 * @session S-DRESS-REHEARSAL-WIPE-AND-SEED
 * @see     docs/FLEETFORGE_DRESS_REHEARSAL_PLAN_2026-06.md
 * @see     scripts/demo_seed.php  (helper patterns borrowed)
 */

declare(strict_types=1);
require '/Users/avi/Documents/fleetforge/config/app.php';
require_once '/Users/avi/Documents/fleetforge/lib/Billing/InvoiceGenerator.php';

// ── Include-guard (FF_REHEARSAL_SEED_INCLUDE) ─────────────────────────────────
// When loaded as a library by scripts/stage_demo_to_production.php, only the
// helper functions and ff_rehearsal_seed_execute() are defined; the production
// guard and top-level execution are skipped. Direct invocation is unchanged.
// (D-STAGE-PROD-TOOL, S-STAGE-DEMO-TO-PRODUCTION)
if (!defined('FF_REHEARSAL_SEED_INCLUDE')) {
    // ── Fail-closed production guard ─────────────────────────────────────────────
    // Re-assert here (independent of demo_wipe) so this script can never seed —
    // and never TRUNCATE equipment — against a production DB. config/app.php
    // line 96 defaults APP_ENV to 'production' when the env var is absent, so an
    // unset/missing .env line also refuses: ambiguity fails closed.
    if (!defined('APP_ENV') || APP_ENV === 'production') {
        $env = defined('APP_ENV') ? APP_ENV : '(undefined — defaults to production)';
        fwrite(STDERR, "\n  HARD REFUSAL — rehearsal_seed.php refuses on production.\n");
        fwrite(STDERR, "  APP_ENV = {$env}\n");
        fwrite(STDERR, "  DB      = " . (defined('FF_DB_NAME') ? FF_DB_NAME : '(unknown)') . "\n");
        fwrite(STDERR, "  Set APP_ENV=development in .env and re-run.\n\n");
        exit(1);
    }

    ff_rehearsal_seed_execute();
}

const RS_USER = 1;  // system/admin user id (FK target for created_by/updated_by)

// ─────────────────────────────────────────────────────────────────────────────
// Helpers (borrowed from scripts/demo_seed.php)
// ─────────────────────────────────────────────────────────────────────────────

/** Date N days before today, as Y-m-d. */
function rs_days_ago(int $n): string { return (new DateTime())->modify("-{$n} days")->format('Y-m-d'); }

/** Date N days after today, as Y-m-d. */
function rs_days_from_now(int $n): string { return (new DateTime())->modify("+{$n} days")->format('Y-m-d'); }

/**
 * Freeze a customer's tax rates onto a lease/invoice snapshot.
 * All rehearsal customers are BC-taxable (tax_rate_id=1, no exemptions), so
 * this returns the raw gst/pst/hst rates from tax_rates unchanged.
 *
 * @return array{gst:string,pst:string,hst:string}
 */
function rs_freeze_tax(int $taxRateId): array
{
    $row = db_row("SELECT gst_rate, pst_rate, hst_rate FROM tax_rates WHERE id = ?", [$taxRateId]);
    if (!$row) {
        throw new RuntimeException("tax_rate id={$taxRateId} not found — wipe preserves tax_rates, so this is a real problem.");
    }
    return ['gst' => $row['gst_rate'], 'pst' => $row['pst_rate'], 'hst' => $row['hst_rate']];
}

/**
 * Build the equipment_snapshot_json a lease freezes at creation.
 * Mirrors scripts/demo_seed.php::buildEquipSnap so the lease snapshot shape
 * matches the rest of the system.
 */
function rs_build_equip_snap(array $u): string
{
    return json_encode([
        'vin'                => $u['vin'],
        'year'               => $u['year'] ? (int) $u['year'] : null,
        'category'           => $u['category'],
        'width_ft'           => $u['width_ft'],
        'height_ft'          => $u['height_ft'],
        'length_ft'          => $u['length_ft'],
        'axle_count'         => $u['axle_count'] ? (int) $u['axle_count'] : null,
        'unit_number'        => $u['unit_number'],
        'license_plate'      => $u['license_plate'],
        'license_state'      => $u['license_state'],
        'template_name'      => $u['template_name'],
        'tracking_provider'  => $u['tracking_provider'],
        'mileage_at_snapshot'=> (int) ($u['mileage'] ?? 0),
        'weight_capacity_lbs'=> $u['weight_capacity_lbs'] ? (int) $u['weight_capacity_lbs'] : null,
    ]);
}

/** Mark an invoice as SENT via direct UPDATE (no AutoEntryBridge / no JE — see docblock). */
function rs_send_invoice(int $invoiceId, string $sentDate, ?string $toEmail): void
{
    db_execute(
        "UPDATE invoices
            SET status = 'sent', sent_date = ?, sent_at = ?, sent_by = ?,
                delivery_method = 'email', sent_to_email = ?
          WHERE id = ?",
        [$sentDate, $sentDate . ' 09:00:00', RS_USER, $toEmail, $invoiceId]
    );
}

/**
 * Execute the full rehearsal seed: Steps 0-9 (clear + templates + units +
 * customers + vendors + leases + invoices + payments + bills + counters).
 *
 * Called by the guarded standalone run (dev only, above) and by
 * scripts/stage_demo_to_production.php after its own production guards.
 * Never invoke without a guard.
 */
function ff_rehearsal_seed_execute(): void
{
        echo "=== FleetForge dress-rehearsal seed ===\n";
    echo "  APP_ENV = " . APP_ENV . "   DB = " . FF_DB_NAME . "\n\n";

    // ─────────────────────────────────────────────────────────────────────────────
    // STEP 0 — Clear (idempotency).  Clear-then-seed so re-runs are reproducible.
    // FK_CHECKS=0 + TRUNCATE for speed (same approach as demo_wipe.php). We also
    // clear samsara_location_history + equipment_status_log: both FK→equipment_units
    // (CASCADE) and would be orphaned by the equipment TRUNCATE. demo_wipe preserves
    // samsara_location_history to keep its GPS demo alive, but SD2=(b) gives us a
    // FRESH equipment set, so the old breadcrumbs are meaningless (and Samsara is
    // not connected in dev anyway). The invoice-number counter is reset so invoice
    // numbers restart at INV-YYYY-00001 each run.
    // ─────────────────────────────────────────────────────────────────────────────
    echo "Step 0 — Clearing tables this seed owns (idempotent)...\n";
    db_execute('SET FOREIGN_KEY_CHECKS = 0', []);
    $rsClear = [
        'payment_allocations', 'payments',
        'invoice_line_items', 'invoices',
        'lease_billing_periods', 'lease_status_log', 'leases',
        'acc_bill_lines', 'acc_bills',
        'customers',
        'vendors',
        'samsara_location_history',   // stale GPS tied to old equipment ids
        'equipment_status_log',       // status log tied to old equipment ids
        'equipment_units',
        'equipment_templates',
    ];
    foreach ($rsClear as $t) {
        $before = (int) (db_row("SELECT COUNT(*) n FROM {$t}", [])['n'] ?? 0);
        db_execute("TRUNCATE TABLE {$t}", []);
        printf("  TRUNCATE %-26s (%d rows)\n", $t, $before);
    }
    db_execute('SET FOREIGN_KEY_CHECKS = 1', []);
    // Reset invoice counter so InvoiceGenerator starts at 00001 (deterministic re-runs).
    db_execute("DELETE FROM settings WHERE `key` LIKE 'invoice.next_number.%'", []);
    echo "  invoice number counter reset\n";

    // ─────────────────────────────────────────────────────────────────────────────
    // STEP 1 — Equipment templates (6).  "rate cards per type" = the template
    // default daily/weekly/monthly + per-km mileage rate. Rates per the plan's
    // heavy-equipment guides. category enum has no 'tractor', so the two tractor
    // templates use category 'other' (matches demo_accounting revenueAcct default).
    // ─────────────────────────────────────────────────────────────────────────────
    echo "\nStep 1 — Equipment templates...\n";
    $templateDefs = [
        'dry_van'  => ['name' => "53' Dry Van Trailer",      'slug' => 'rehearsal-dry-van-53',     'category' => 'dry_van',   'brand' => 'Wabash',       'model' => 'DuraPlate 53',        'len' => '53.00', 'wid' => '8.50', 'hgt' => '13.50', 'axles' => 2, 'cap' => 45000, 'daily' => '45.00',  'weekly' => '270.00', 'monthly' => '950.00',  'mileage' => '0.1200'],
        'reefer'   => ['name' => "53' Reefer Trailer",        'slug' => 'rehearsal-reefer-53',      'category' => 'reefer',    'brand' => 'Great Dane',   'model' => 'Everest SS Reefer',   'len' => '53.00', 'wid' => '8.50', 'hgt' => '13.50', 'axles' => 2, 'cap' => 44000, 'daily' => '85.00',  'weekly' => '510.00', 'monthly' => '1800.00', 'mileage' => '0.1800'],
        'flatbed'  => ['name' => "53' Flatbed Trailer",       'slug' => 'rehearsal-flatbed',        'category' => 'flatbed',   'brand' => 'Utility',      'model' => 'Flatbed 4000A',       'len' => '53.00', 'wid' => '8.50', 'hgt' => '5.00',  'axles' => 2, 'cap' => 48000, 'daily' => '55.00',  'weekly' => '330.00', 'monthly' => '1150.00', 'mileage' => '0.1400'],
        'step_deck'=> ['name' => "Step Deck Trailer",         'slug' => 'rehearsal-step-deck',      'category' => 'step_deck', 'brand' => 'Fontaine',     'model' => 'Infinity Step Deck',  'len' => '53.00', 'wid' => '8.50', 'hgt' => '10.00', 'axles' => 2, 'cap' => 48000, 'daily' => '65.00',  'weekly' => '390.00', 'monthly' => '1350.00', 'mileage' => '0.1500'],
        'day_cab'  => ['name' => "Day Cab Tractor",           'slug' => 'rehearsal-day-cab-tractor','category' => 'other',     'brand' => 'Freightliner', 'model' => 'Cascadia Day Cab',    'len' => '24.00', 'wid' => '8.50', 'hgt' => '10.50', 'axles' => 3, 'cap' => null,  'daily' => '120.00', 'weekly' => '720.00', 'monthly' => '2600.00', 'mileage' => '0.2200'],
        'sleeper'  => ['name' => "Sleeper Tractor",           'slug' => 'rehearsal-sleeper-tractor','category' => 'other',     'brand' => 'Kenworth',     'model' => 'T680 76in Sleeper',   'len' => '28.00', 'wid' => '8.50', 'hgt' => '11.00', 'axles' => 3, 'cap' => null,  'daily' => '150.00', 'weekly' => '900.00', 'monthly' => '3200.00', 'mileage' => '0.2500'],
    ];
    $templateIds = [];
    $tplSort = 0;
    foreach ($templateDefs as $key => $t) {
        $templateIds[$key] = db_insert('equipment_templates', [
            'name'                        => $t['name'],
            'slug'                        => $t['slug'],
            'description'                 => $t['name'] . ' — rehearsal fleet template',
            'category'                    => $t['category'],
            'brand'                       => $t['brand'],
            'model'                       => $t['model'],
            'default_length_ft'           => $t['len'],
            'default_width_ft'            => $t['wid'],
            'default_height_ft'           => $t['hgt'],
            'default_weight_capacity_lbs' => $t['cap'],
            'default_axle_count'          => $t['axles'],
            'default_ownership_type'      => 'owned',
            'default_tracking_provider'   => 'none',
            'default_daily_rate'          => $t['daily'],
            'default_weekly_rate'         => $t['weekly'],
            'default_monthly_rate'        => $t['monthly'],
            'default_mileage_rate'        => $t['mileage'],   // NOT NULL (D135) — never seed 0 for these revenue templates
            'default_currency'            => 'CAD',
            'default_mileage_unit'        => 'km',
            'is_active'                   => 1,
            'sort_order'                  => $tplSort++,
            'created_by'                  => RS_USER,
        ]);
        printf("  id=%d %-22s %s/d %s/wk %s/mo %s/km\n", $templateIds[$key], $t['name'], $t['daily'], $t['weekly'], $t['monthly'], $t['mileage']);
    }

    // ─────────────────────────────────────────────────────────────────────────────
    // STEP 2 — Equipment units (25).  Deterministic unit numbers, synthetic 17-char
    // VINs, years 2018-2024, all owned, BC-plated, status 'available' (leases flip
    // the leased ones to on_lease / available below).
    // ─────────────────────────────────────────────────────────────────────────────
    echo "\nStep 2 — Equipment units...\n";
    // [template key, unit-number prefix, count, base-year, mileage band]
    $unitPlan = [
        ['dry_van',   'T53', 8, 2019, 80000],   // T5301..T5308
        ['reefer',    'T62', 5, 2020, 60000],   // T6201..T6205
        ['flatbed',   'T48', 4, 2018, 95000],   // T4801..T4804
        ['step_deck', 'T35', 3, 2021, 40000],   // T3501..T3503
        ['day_cab',   'P10', 3, 2022, 220000],  // P1001..P1003
        ['sleeper',   'P20', 2, 2023, 180000],  // P2001..P2002
    ];
    // VIN type codes (kept 2 chars so the synthetic VIN is a clean 17 chars)
    $vinType = ['dry_van' => 'DV', 'reefer' => 'RF', 'flatbed' => 'FB', 'step_deck' => 'SD', 'day_cab' => 'DC', 'sleeper' => 'SL'];
    $units = [];          // flat list of seeded unit rows (with template fields merged) for lease wiring
    $unitSeq = 0;
    foreach ($unitPlan as [$tplKey, $prefix, $count, $baseYear, $baseMileage]) {
        $tpl = $templateDefs[$tplKey];
        for ($i = 1; $i <= $count; $i++) {
            $unitSeq++;
            $year       = $baseYear + (($i - 1) % 6);            // spread 2018-2024 within band
            $unitNumber = sprintf('%s%02d', $prefix, $i);        // e.g. T5301
            // Synthetic 17-char VIN: '1FF' + 2-char type + 2-digit year + 10-digit seq
            $vin        = sprintf('1FF%s%02d%010d', $vinType[$tplKey], $year % 100, $unitSeq);
            $mileage    = $baseMileage + ($i * 3137);            // deterministic spread, never 0
            $unitId = db_insert('equipment_units', [
                'template_id'         => $templateIds[$tplKey],
                'unit_number'         => $unitNumber,
                'vin'                 => $vin,
                'year'                => $year,
                'tracking_provider'   => 'none',
                'ownership_type'      => 'owned',                // NOT NULL, no DB default — must set
                'yard_location'       => 'Surrey Yard',
                'length_ft'           => $tpl['len'],
                'width_ft'            => $tpl['wid'],
                'height_ft'           => $tpl['hgt'],
                'weight_capacity_lbs' => $tpl['cap'],
                'axle_count'          => $tpl['axles'],
                'license_plate'       => sprintf('BC%05d', 30000 + $unitSeq),
                'license_state'       => 'BC',
                'status'              => 'available',
                'mileage'             => $mileage,
                'notes'               => $tpl['name'] . ' — rehearsal fleet unit',
                'created_by'          => RS_USER,
                'updated_by'          => RS_USER,
            ]);
            // Keep a denormalized row for lease wiring (template fields + ids).
            $units[$unitNumber] = [
                'id'                  => $unitId,
                'template_id'         => $templateIds[$tplKey],
                'template_key'        => $tplKey,
                'template_name'       => $tpl['name'],
                'category'            => $tpl['category'],
                'unit_number'         => $unitNumber,
                'vin'                 => $vin,
                'year'                => $year,
                'length_ft'           => $tpl['len'],
                'width_ft'            => $tpl['wid'],
                'height_ft'           => $tpl['hgt'],
                'weight_capacity_lbs' => $tpl['cap'],
                'axle_count'          => $tpl['axles'],
                'license_plate'       => sprintf('BC%05d', 30000 + $unitSeq),
                'license_state'       => 'BC',
                'tracking_provider'   => 'none',
                'mileage'             => $mileage,
                'daily_rate'          => $tpl['daily'],
                'weekly_rate'         => $tpl['weekly'],
                'monthly_rate'        => $tpl['monthly'],
                'mileage_rate'        => $tpl['mileage'],
            ];
        }
        printf("  %d× %-22s (%s%02d..%s%02d)\n", $count, $tpl['name'], $prefix, 1, $prefix, $count);
    }
    printf("  Total units: %d\n", count($units));

    // ─────────────────────────────────────────────────────────────────────────────
    // STEP 3 — Customers (12 BC trucking companies).  All province=BC,
    // country=Canada, BC-taxable (tax_rate_id=1), CAD, Net 30 default.
    // ─────────────────────────────────────────────────────────────────────────────
    echo "\nStep 3 — Customers...\n";
    $customerDefs = [
        ['company' => 'Fraser Valley Freight Ltd.',     'contact' => 'Harjit Sandhu',   'city' => 'Abbotsford',      'pc' => 'V2T 6H2', 'area' => '604', 'domain' => 'fvfreight.ca',            'addr' => '31420 Peardonville Rd',  'risk' => 'low',    'terms' => 'Net 30'],
        ['company' => 'Coastal Haul Logistics Inc.',    'contact' => 'Marie Tremblay',  'city' => 'Surrey',          'pc' => 'V3W 1A1', 'area' => '604', 'domain' => 'coastalhaul.ca',          'addr' => '12880 80th Ave',         'risk' => 'low',    'terms' => 'Net 30'],
        ['company' => 'Pacific Rim Transport Ltd.',     'contact' => 'David Cheung',    'city' => 'Delta',           'pc' => 'V3M 6R9', 'area' => '604', 'domain' => 'pacificrimtransport.ca',  'addr' => '7575 Progress Way',      'risk' => 'low',    'terms' => 'Net 45'],
        ['company' => 'Cascade Carriers Ltd.',          'contact' => 'Brian Olsen',     'city' => 'Langley',         'pc' => 'V2Y 1N5', 'area' => '604', 'domain' => 'cascadecarriers.ca',      'addr' => '20678 Langley Bypass',   'risk' => 'medium', 'terms' => 'Net 30'],
        ['company' => 'Sumas Mountain Hauling Ltd.',    'contact' => 'Gurpreet Dhillon','city' => 'Abbotsford',      'pc' => 'V3G 2J5', 'area' => '604', 'domain' => 'sumasmountainhauling.ca', 'addr' => '4521 Sumas Mountain Rd', 'risk' => 'medium', 'terms' => 'Net 30'],
        ['company' => 'Delta Port Drayage Ltd.',        'contact' => 'Amrit Gill',      'city' => 'Delta',           'pc' => 'V4K 3N3', 'area' => '604', 'domain' => 'deltaportdrayage.ca',     'addr' => '5500 Tilbury Rd',        'risk' => 'low',    'terms' => 'Net 30'],
        ['company' => 'Interior Freight Systems Inc.',  'contact' => 'Karen Whitford',  'city' => 'Kamloops',        'pc' => 'V2C 6T7', 'area' => '250', 'domain' => 'interiorfreight.ca',      'addr' => '1885 Kryczka Pl',        'risk' => 'low',    'terms' => 'Net 30'],
        ['company' => 'Cariboo Bulk Transport Ltd.',    'contact' => 'Wade Forsberg',   'city' => 'Prince George',   'pc' => 'V2N 4X8', 'area' => '250', 'domain' => 'caribootransport.ca',     'addr' => '2055 Boundary Rd',       'risk' => 'medium', 'terms' => 'Net 30'],
        ['company' => 'Westshore Logistics Inc.',       'contact' => 'Priya Nair',      'city' => 'Richmond',        'pc' => 'V6X 1Z5', 'area' => '604', 'domain' => 'westshorelogistics.ca',   'addr' => '13551 Vulcan Way',       'risk' => 'low',    'terms' => 'Net 45'],
        ['company' => 'Okanagan Cartage Ltd.',          'contact' => 'Sam Pellegrino',  'city' => 'Kelowna',         'pc' => 'V1X 7T2', 'area' => '250', 'domain' => 'okanagancartage.ca',      'addr' => '1860 Windsor Rd',        'risk' => 'medium', 'terms' => 'Net 30'],
        ['company' => 'Pitt River Hauling Co.',         'contact' => 'Lucas Reyes',     'city' => 'Port Coquitlam',  'pc' => 'V3C 5W8', 'area' => '604', 'domain' => 'pittriverhauling.ca',     'addr' => '1521 Broadway St',       'risk' => 'low',    'terms' => 'Net 30'],
        ['company' => 'Sea-to-Sky Freight Ltd.',        'contact' => 'Emma Larsson',    'city' => 'Squamish',        'pc' => 'V8B 0N5', 'area' => '604', 'domain' => 'seatoskyfreight.ca',      'addr' => '39012 Discovery Way',    'risk' => 'low',    'terms' => 'Net 30'],
    ];
    $customerIds = [];
    foreach ($customerDefs as $idx => $c) {
        $local = strtolower(explode(' ', $c['contact'])[0]);   // first-name local part
        $phone = sprintf('%s-555-%04d', $c['area'], 1000 + $idx);
        $id = db_insert('customers', [
            'company_name'  => $c['company'],
            'contact_name'  => $c['contact'],
            'email'         => $local . '@' . $c['domain'],
            'phone'         => $phone,
            'address'       => $c['addr'],
            'city'          => $c['city'],
            'province'      => 'BC',
            'country'       => 'Canada',   // see docblock NOTE (not 'CA')
            'postal_code'   => $c['pc'],
            'currency'      => 'CAD',
            'mileage_unit'  => 'km',
            'tax_rate_id'   => 1,          // BC GST+PST (5% + 7%)
            'gst_exempt'    => 0, 'pst_exempt' => 0, 'tax_exempt' => 0,
            'billing_cycle' => 'monthly',
            'payment_terms' => $c['terms'],
            'credit_limit'  => '50000.00',
            'risk_score'    => $c['risk'],
            'status'        => 'active',
            'notes'         => 'BC trucking carrier — dress-rehearsal customer.',
            'created_by'    => RS_USER,
            'updated_by'    => RS_USER,
        ]);
        $customerIds[$idx] = $id;
        printf("  id=%d %-32s %s, BC\n", $id, $c['company'], $c['city']);
    }

    // ─────────────────────────────────────────────────────────────────────────────
    // STEP 4 — Vendors (4).  vendor_type enum is (maintenance,repair,parts,
    // inspection,towing,other) — fuel supplier + finance lender map to 'other'.
    // ─────────────────────────────────────────────────────────────────────────────
    echo "\nStep 4 — Vendors...\n";
    $vendorDefs = [
        'maintenance' => ['name' => 'Fraser Valley Truck & Trailer Repair', 'vendor_type' => 'maintenance', 'contact' => 'Doug McRae',     'city' => 'Abbotsford', 'phone' => '604-555-7100', 'domain' => 'fvtrucktrailer.ca', 'hourly' => '145.00', 'rating' => 5],
        'parts'       => ['name' => 'Pacific Truck Parts Ltd.',             'vendor_type' => 'parts',       'contact' => 'Nadia Petrov',   'city' => 'Surrey',     'phone' => '604-555-7200', 'domain' => 'pacifictruckparts.ca','hourly' => null,    'rating' => 4],
        'fuel'        => ['name' => 'Coastal Fuels Inc.',                   'vendor_type' => 'other',       'contact' => 'Trevor Lund',    'city' => 'Delta',      'phone' => '604-555-7300', 'domain' => 'coastalfuels.ca',   'hourly' => null,    'rating' => 4],
        'finance'     => ['name' => 'BC Equipment Finance Corp.',           'vendor_type' => 'other',       'contact' => 'Janet Soo',      'city' => 'Vancouver',  'phone' => '604-555-7400', 'domain' => 'bcequipfinance.ca', 'hourly' => null,    'rating' => 5],
    ];
    $vendorIds = [];
    foreach ($vendorDefs as $key => $v) {
        $local = strtolower(explode(' ', $v['contact'])[0]);
        $vendorIds[$key] = db_insert('vendors', [
            'name'          => $v['name'],
            'vendor_type'   => $v['vendor_type'],
            'contact_name'  => $v['contact'],
            'email'         => $local . '@' . $v['domain'],
            'phone'         => $v['phone'],
            'city'          => $v['city'],
            'state'         => 'BC',
            'specializations'=> json_encode([$key]),
            'hourly_rate'   => $v['hourly'],
            'rating'        => $v['rating'],
            'currency'      => 'CAD',
            'notes'         => 'Dress-rehearsal vendor.',
            'created_by'    => RS_USER,
        ]);
        printf("  id=%d %-38s (%s)\n", $vendorIds[$key], $v['name'], $v['vendor_type']);
    }

    // ─────────────────────────────────────────────────────────────────────────────
    // STEP 5 — Leases (6, varied lifecycle).  Each references a fresh unit; rates
    // come straight from the unit's template defaults (never 0). Equipment status
    // is synced (active→on_lease, completed→available).
    //
    // Lifecycle map:
    //   L1 just-started (7d ago, 1 sent unpaid invoice)        → dry van
    //   L2 mid-cycle partial (60d, 2 inv: 1 paid 1 outstanding)→ reefer   [E2 target]
    //   L3 mid-cycle current (45d, 2 inv: all paid)            → flatbed
    //   L4 ending soon (end +14d, 2 inv: current/sent)         → step deck
    //   L5 long-term (180d, 6 monthly inv: 5 paid 1 out)       → day-cab tractor
    //   L6 recently closed (returned 10d ago, 1 final paid)    → sleeper tractor
    // ─────────────────────────────────────────────────────────────────────────────
    echo "\nStep 5 — Leases...\n";
    $leasePlan = [
        'L1' => ['label' => 'Just started — dry van',         'cust' => 0, 'unit' => 'T5301', 'status' => 'active',    'start' => rs_days_ago(7),   'end' => rs_days_from_now(358), 'next_bill' => rs_days_from_now(23)],
        'L2' => ['label' => 'Mid-cycle partial — reefer',     'cust' => 1, 'unit' => 'T6201', 'status' => 'active',    'start' => rs_days_ago(60),  'end' => rs_days_from_now(305), 'next_bill' => rs_days_from_now(1)],
        'L3' => ['label' => 'Mid-cycle current — flatbed',    'cust' => 2, 'unit' => 'T4801', 'status' => 'active',    'start' => rs_days_ago(45),  'end' => rs_days_from_now(320), 'next_bill' => rs_days_from_now(15)],
        'L4' => ['label' => 'Ending soon — step deck',        'cust' => 3, 'unit' => 'T3501', 'status' => 'active',    'start' => rs_days_ago(46),  'end' => rs_days_from_now(14),  'next_bill' => rs_days_from_now(14)],
        'L5' => ['label' => 'Long-term — day cab tractor',    'cust' => 6, 'unit' => 'P1001', 'status' => 'active',    'start' => rs_days_ago(180), 'end' => rs_days_from_now(185), 'next_bill' => rs_days_from_now(2)],
        'L6' => ['label' => 'Recently closed — sleeper',      'cust' => 8, 'unit' => 'P2001', 'status' => 'completed', 'start' => rs_days_ago(38),  'end' => rs_days_ago(10),       'return' => rs_days_ago(10)],
    ];
    $leaseIds = [];
    $contractSeq = 0;
    foreach ($leasePlan as $lk => $l) {
        $unit     = $units[$l['unit']];
        $custIdx  = $l['cust'];
        $custDef  = $customerDefs[$custIdx];
        $custId   = $customerIds[$custIdx];
        $tax      = rs_freeze_tax(1);
        $contractSeq++;

        $row = [
            'contract_number'         => sprintf('CN-RHRSL-%04d', $contractSeq),
            'customer_id'             => $custId,
            'equipment_unit_id'       => $unit['id'],
            'customer_name_snapshot'  => $custDef['contact'],
            'company_name_snapshot'   => $custDef['company'],
            'unit_number_snapshot'    => $unit['unit_number'],
            'template_name_snapshot'  => $unit['template_name'],
            'equipment_snapshot_json' => rs_build_equip_snap($unit),
            'status'                  => $l['status'],
            'start_date'              => $l['start'],
            'end_date'                => $l['end'],
            'actual_return_date'      => $l['return'] ?? null,
            'daily_rate'              => $unit['daily_rate'],
            'weekly_rate'             => $unit['weekly_rate'],
            'monthly_rate'            => $unit['monthly_rate'],
            'mileage_rate'            => $unit['mileage_rate'],
            'currency'                => 'CAD',
            'mileage_unit'            => 'km',
            'billing_cycle'           => 'monthly',
            'estimated_mileage'       => '0.00',
            'actual_mileage'          => '0.00',
            'gst_exempt'              => 0,
            'pst_exempt'              => 0,
            'tax_exempt'              => 0,
            'tax_rate_gst'            => $tax['gst'],
            'tax_rate_pst'            => $tax['pst'],
            'tax_rate_hst'            => $tax['hst'],
            'discount_type'           => 'none',
            'discount_value'          => '0.00',
            'insurance_opt_in'        => 0,
            'insurance_cost'          => '0.00',
            'warranty_opt_in'         => 0,
            'warranty_cost'           => '0.00',
            'next_billing_date'       => $l['next_bill'] ?? null,
            'last_billed_date'        => null,
            'notes'                   => $l['label'],
            'created_by'              => RS_USER,
            'updated_by'              => RS_USER,
        ];
        if ($l['status'] === 'completed') {
            $row['closed_at']         = ($l['return'] ?? $l['end']) . ' 16:00:00';
            $row['closed_by_user_id'] = RS_USER;
        }
        $leaseId = db_insert('leases', $row);
        $leaseIds[$lk] = $leaseId;

        // Sync unit status (active→on_lease, completed→available).
        $unitStatus = $l['status'] === 'active' ? 'on_lease' : 'available';
        db_execute("UPDATE equipment_units SET status = ?, updated_by = ? WHERE id = ?", [$unitStatus, RS_USER, $unit['id']]);

        db_insert('lease_status_log', [
            'lease_id'   => $leaseId,
            'old_status' => 'none',
            'new_status' => $l['status'],
            'notes'      => 'Rehearsal seed: ' . $l['label'],
            'changed_by' => 'rehearsal-seeder',
            'user_id'    => RS_USER,
        ]);
        printf("  id=%d %-9s %-32s unit=%s %s/mo\n", $leaseId, $l['status'], $l['label'], $unit['unit_number'], $unit['monthly_rate']);
    }

    // ─────────────────────────────────────────────────────────────────────────────
    // STEP 6 — Invoices (via InvoiceGenerator) + SEND.  Periods are explicit
    // [start,end] inclusive ranges with no gaps/overlaps. 'pay' marks which
    // periods get a payment in Step 7. InvoiceGenerator creates each as 'draft';
    // we immediately SEND every generated invoice (so AR reflects issued invoices
    // per Path-B: outstanding_balance counts sent/partially_paid/overdue).
    // ─────────────────────────────────────────────────────────────────────────────
    echo "\nStep 6 — Invoices...\n";
    $invoicePlan = [
        // lease => [ [start, end, billing_type, invoice_type, pay(bool)], ... ]
        'L1' => [[rs_days_ago(7),   rs_days_ago(0),   'single_period', 'regular', false]],
        'L2' => [[rs_days_ago(60),  rs_days_ago(31),  'partial_start', 'regular', true ],
                 [rs_days_ago(30),  rs_days_ago(0),   'full_month',    'regular', false]],
        'L3' => [[rs_days_ago(45),  rs_days_ago(16),  'partial_start', 'regular', true ],
                 [rs_days_ago(15),  rs_days_ago(0),   'full_month',    'regular', true ]],
        'L4' => [[rs_days_ago(46),  rs_days_ago(17),  'partial_start', 'regular', false],
                 [rs_days_ago(16),  rs_days_ago(0),   'full_month',    'regular', false]],
        'L5' => [[rs_days_ago(180), rs_days_ago(151), 'partial_start', 'regular', true ],
                 [rs_days_ago(150), rs_days_ago(121), 'full_month',    'regular', true ],
                 [rs_days_ago(120), rs_days_ago(91),  'full_month',    'regular', true ],
                 [rs_days_ago(90),  rs_days_ago(61),  'full_month',    'regular', true ],
                 [rs_days_ago(60),  rs_days_ago(31),  'full_month',    'regular', true ],
                 [rs_days_ago(30),  rs_days_ago(0),   'full_month',    'regular', false]],
        'L6' => [[rs_days_ago(38),  rs_days_ago(10),  'single_period', 'final',   true ]],
    ];
    $gen = new \FleetForge\Billing\InvoiceGenerator();
    $invoicesByLease = [];   // lk => [ ['id','total','pay','period_end'], ... ]
    $invoiceTotal = 0;
    foreach ($invoicePlan as $lk => $periods) {
        $leaseId = $leaseIds[$lk];
        $custIdx = $leasePlan[$lk]['cust'];
        $custEmail = strtolower(explode(' ', $customerDefs[$custIdx]['contact'])[0]) . '@' . $customerDefs[$custIdx]['domain'];
        foreach ($periods as [$pStart, $pEnd, $billingType, $invType, $pay]) {
            $res = $gen->createFromLease([
                'lease_id'          => $leaseId,
                'period_start'      => $pStart,
                'period_end'        => $pEnd,
                'billing_type'      => $billingType,
                'invoice_type'      => $invType,
                'generation_source' => 'cron',
                'auto_generated'    => 1,
                'created_by'        => RS_USER,
            ]);
            // Sanity: a rehearsal invoice must never be zero (silent-zero-rate bug class).
            if (bccomp((string) $res['total_amount'], '0.00', 2) <= 0) {
                throw new RuntimeException("ZERO/negative invoice {$res['invoice_number']} for {$lk} {$pStart}->{$pEnd} — rate completeness failure.");
            }
            // Send it (sent_date = the day after the period closed, but never future).
            $sentDate = min($pEnd, rs_days_ago(0));
            rs_send_invoice((int) $res['invoice_id'], $sentDate, $custEmail);
            $invoicesByLease[$lk][] = [
                'id'         => (int) $res['invoice_id'],
                'number'     => $res['invoice_number'],
                'total'      => (string) $res['total_amount'],
                'pay'        => $pay,
                'period_end' => $pEnd,
            ];
            $invoiceTotal++;
            printf("  %-3s %s  %s..%s  $%s%s\n", $lk, $res['invoice_number'], $pStart, $pEnd, $res['total_amount'], $pay ? '  (will pay)' : '');
        }
        // Stamp last_billed_date on active leases = most-recent period end.
        if ($leasePlan[$lk]['status'] === 'active') {
            $lastEnd = end($periods)[1];
            db_execute("UPDATE leases SET last_billed_date = ? WHERE id = ?", [$lastEnd, $leaseId]);
        }
    }
    printf("  Total invoices: %d (all SENT)\n", $invoiceTotal);

    // ─────────────────────────────────────────────────────────────────────────────
    // STEP 7 — Payments (4).  One payment per lease that has paid periods (L2, L3,
    // L5, L6). Each payment is allocated in full to its lease's paid invoices and
    // the invoice is marked 'paid'. Methods mix cheque / EFT(ach) / e-transfer.
    // All amounts CAD (FX 1.0), money via bcmath.
    // ─────────────────────────────────────────────────────────────────────────────
    echo "\nStep 7 — Payments...\n";
    $paymentSpecs = [
        // lease => [method, reference, bank, pay_date]
        'L2' => ['check',      'CHQ-10241',     'RBC',         rs_days_ago(28)],
        'L3' => ['ach',        'EFT-20260530',  'TD Canada',   rs_days_ago(1)],
        'L5' => ['e_transfer', 'ETR-99381',     'BMO',         rs_days_ago(27)],
        'L6' => ['check',      'CHQ-10255',     'RBC',         rs_days_ago(8)],
    ];
    $paySeq = 0;
    foreach ($paymentSpecs as $lk => [$method, $ref, $bank, $payDate]) {
        $custIdx = $leasePlan[$lk]['cust'];
        $custId  = $customerIds[$custIdx];
        $toPay   = array_values(array_filter($invoicesByLease[$lk], fn($iv) => $iv['pay']));
        if (!$toPay) {
            throw new RuntimeException("Payment spec for {$lk} but no payable invoices — invoice plan / payment spec out of sync.");
        }

        // Payment amount = bcmath sum of the invoices it settles.
        $amount = '0.00';
        foreach ($toPay as $iv) {
            $amount = bcadd($amount, $iv['total'], 2);
        }

        $paySeq++;
        $paymentId = db_insert('payments', [
            'payment_number'       => sprintf('PMT-2026-%05d', $paySeq),
            'customer_id'          => $custId,
            'amount'               => $amount,
            'currency'             => 'CAD',
            'exchange_rate_to_cad' => '1.000000',
            'amount_in_cad'        => $amount,
            'payment_method'       => $method,
            'reference_number'     => $ref,
            'bank_name'            => $bank,
            'payment_date'         => $payDate,
            'received_at'          => $payDate . ' 10:00:00',
            'status'               => 'cleared',
            'notes'                => 'Rehearsal seed payment for ' . $lk,
            'recorded_by'          => RS_USER,
        ]);

        // Allocate in full to each paid invoice + mark it paid.
        foreach ($toPay as $iv) {
            db_insert('payment_allocations', [
                'payment_id'      => $paymentId,
                'invoice_id'      => $iv['id'],
                'amount'          => $iv['total'],
                'currency'        => 'CAD',
                'allocation_type' => 'manual',
                'allocated_by'    => RS_USER,
            ]);
            db_execute(
                "UPDATE invoices SET amount_paid = ?, balance_due = '0.00', status = 'paid', paid_date = ? WHERE id = ?",
                [$iv['total'], $payDate, $iv['id']]
            );
        }
        printf("  id=%d %-12s %s  $%s  (%d invoice%s)\n", $paymentId, $method, $lk, $amount, count($toPay), count($toPay) === 1 ? '' : 's');
    }

    // ─────────────────────────────────────────────────────────────────────────────
    // STEP 8 — Bills (3, AP).  One each from the maintenance / parts / fuel vendor.
    // status 'approved' (entered + approved, awaiting payment), NO journal entry
    // (operational-layer-only — see docblock). Tax = BC GST 5% + PST 7% via bcmath.
    // period_id resolved from bill_date (all recent → open periods).
    // ─────────────────────────────────────────────────────────────────────────────
    echo "\nStep 8 — Bills...\n";
    /** Resolve the acc_period id covering a date (bills.period_id is NOT NULL). */
    $periodForDate = function (string $date): int {
        $row = db_row("SELECT id FROM acc_periods WHERE ? BETWEEN start_date AND end_date", [$date]);
        if (!$row) throw new RuntimeException("No acc_period covers {$date}.");
        return (int) $row['id'];
    };
    /** GL expense account id by code (chart of accounts preserved by the wipe). */
    $acctByCode = function (string $code): int {
        $row = db_row("SELECT id FROM acc_accounts WHERE code = ?", [$code]);
        if (!$row) throw new RuntimeException("acc_account code {$code} not found.");
        return (int) $row['id'];
    };
    $billDefs = [
        ['vendor' => 'maintenance', 'acct' => '6010', 'date' => rs_days_ago(20), 'subtotal' => '2450.00', 'desc' => 'Brake + ABS service and annual CVI prep — trailer fleet'],
        ['vendor' => 'parts',       'acct' => '6020', 'date' => rs_days_ago(12), 'subtotal' => '1180.00', 'desc' => 'Replacement LED lighting kits + air lines — restock'],
        ['vendor' => 'fuel',        'acct' => '6040', 'date' => rs_days_ago(6),  'subtotal' => '3675.00', 'desc' => 'Bulk diesel delivery — yard fuel tank top-up'],
    ];
    $billSeq = 0;
    foreach ($billDefs as $b) {
        $billSeq++;
        $subtotal = $b['subtotal'];
        $gst      = bcmul($subtotal, '0.05', 2);    // BC GST 5%
        $pst      = bcmul($subtotal, '0.07', 2);    // BC PST 7%
        $taxTotal = bcadd($gst, $pst, 2);
        $total    = bcadd($subtotal, $taxTotal, 2);
        $billDate = $b['date'];
        $billId = db_insert('acc_bills', [
            'bill_number'        => sprintf('BILL-2026-%05d', $billSeq),
            'vendor_id'          => $vendorIds[$b['vendor']],
            'vendor_bill_number' => sprintf('INV-%s-%04d', strtoupper(substr($b['vendor'], 0, 3)), 1000 + $billSeq),
            'bill_date'          => $billDate,
            'due_date'           => (new DateTime($billDate))->modify('+30 days')->format('Y-m-d'),
            'period_id'          => $periodForDate($billDate),
            'status'             => 'approved',     // entered + approved, awaiting payment (no JE — see docblock)
            'currency'           => 'CAD',
            'subtotal'           => $subtotal,
            'tax_gst_amount'     => $gst,
            'tax_pst_amount'     => $pst,
            'tax_total'          => $taxTotal,
            'total_amount'       => $total,
            'amount_paid'        => '0.00',
            'balance_due'        => $total,
            'notes'              => $b['desc'],
            'created_by'         => RS_USER,
        ]);
        db_insert('acc_bill_lines', [
            'bill_id'        => $billId,
            'account_id'     => $acctByCode($b['acct']),
            'description'    => $b['desc'],
            'quantity'       => '1.0000',
            'unit_cost'      => $subtotal,
            'amount'         => $subtotal,
            'tax_gst_amount' => $gst,
            'tax_pst_amount' => $pst,
            'sort_order'     => 1,
        ]);
        printf("  id=%d %-12s $%s (sub %s + tax %s)  due %s\n", $billId, $b['vendor'], $total, $subtotal, $taxTotal, (new DateTime($billDate))->modify('+30 days')->format('Y-m-d'));
    }

    // ─────────────────────────────────────────────────────────────────────────────
    // STEP 9 — Recompute denormalized counters (Path-B semantics, per project memory
    // project_path_b_counter_semantics + scripts/demo_seed.php).
    //   customers.outstanding_balance = SUM(balance_due) of invoices in
    //     status IN ('sent','partially_paid','overdue) — drafts/voids excluded.
    //   customers.total_revenue       = SUM(amount_paid).
    //   equipment_units.lease_count / total_revenue recomputed from leases/invoices.
    //   vendors.total_spent           = SUM of paid bills (all approved-unpaid → 0).
    // ─────────────────────────────────────────────────────────────────────────────
    echo "\nStep 9 — Recomputing counters...\n";
    db_execute(
        "UPDATE customers c SET
            lease_count = (SELECT COUNT(*) FROM leases WHERE customer_id = c.id AND deleted_at IS NULL),
            active_lease_count = (SELECT COUNT(*) FROM leases WHERE customer_id = c.id AND status = 'active' AND deleted_at IS NULL),
            total_revenue = COALESCE((SELECT SUM(amount_paid) FROM invoices WHERE customer_id = c.id AND deleted_at IS NULL), 0),
            outstanding_balance = COALESCE((SELECT SUM(balance_due) FROM invoices WHERE customer_id = c.id AND deleted_at IS NULL AND status IN ('sent','partially_paid','overdue')), 0)
          WHERE deleted_at IS NULL",
        []
    );
    db_execute(
        "UPDATE equipment_units eu SET
            lease_count = (SELECT COUNT(*) FROM leases WHERE equipment_unit_id = eu.id AND deleted_at IS NULL),
            total_revenue = COALESCE(
              (SELECT SUM(i.amount_paid) FROM invoices i
                 JOIN leases l ON l.id = i.lease_id
                WHERE l.equipment_unit_id = eu.id AND i.deleted_at IS NULL), 0)
          WHERE deleted_at IS NULL",
        []
    );
    db_execute(
        "UPDATE vendors v SET total_spent = COALESCE(
            (SELECT SUM(amount_paid) FROM acc_bills WHERE vendor_id = v.id), 0)
          WHERE deleted_at IS NULL",
        []
    );
    echo "  Counters recomputed (customers / equipment / vendors).\n";

    // ─────────────────────────────────────────────────────────────────────────────
    // Summary
    // ─────────────────────────────────────────────────────────────────────────────
    echo "\n=== Summary ===\n";
    foreach (['equipment_templates','equipment_units','customers','vendors','leases','invoices','payments','acc_bills'] as $t) {
        printf("  %-20s %d\n", $t, (int) db_row("SELECT COUNT(*) n FROM {$t}", [])['n']);
    }
    $ar  = db_row("SELECT COALESCE(SUM(balance_due),0) t FROM invoices WHERE deleted_at IS NULL AND status IN ('sent','partially_paid','overdue')", [])['t'];
    $rev = db_row("SELECT COALESCE(SUM(amount_paid),0) t FROM invoices WHERE deleted_at IS NULL", [])['t'];
    $ap  = db_row("SELECT COALESCE(SUM(balance_due),0) t FROM acc_bills", [])['t'];
    printf("  Outstanding AR (sent+): $%s\n", number_format((float) $ar, 2));
    printf("  Collected (paid):       $%s\n", number_format((float) $rev, 2));
    printf("  Outstanding AP (bills): $%s\n", number_format((float) $ap, 2));
    echo "\n=== Rehearsal seed complete ===\n";

}
