<?php
declare(strict_types=1);

/**
 * FleetForge — Lease Activate API
 *
 * @file        api/v1/leases/activate.php
 * @description Transitions a lease from 'pending' → 'active'.
 *
 *              State machine (spec §6):
 *                pending → active (this endpoint)
 *                active → completed | cancelled
 *
 *              Concurrency (D20): acquires FOR UPDATE lock on equipment_unit.
 *              Re-validates unit status at lock time — prevents race where unit
 *              was leased between create and activate.
 *
 *              On activation:
 *              1. Validate lease is pending
 *              2. FOR UPDATE lock on unit — check still available
 *              3. Update lease status → 'active'
 *              4. Update equipment_unit status → 'on_lease'
 *              5. Write equipment_status_log entry
 *              6. Write lease_status_log entry
 *              7. Write audit_log entry
 *
 *              Invoice 1 will be generated by InvoiceGenerator (not yet built — S009+).
 *              This endpoint stubs the trigger point with a comment.
 *
 * @method      POST
 * @body        JSON — id (lease id, required)
 * @auth        Session required; require_permission('leases','edit')
 * @returns     200 { id, status } | 409 INVALID_TRANSITION | 409 UNIT_UNAVAILABLE | 404 NOT_FOUND
 *
 * @depends     api/bootstrap.php
 * @spec        FLEETFORGE_SPEC_FINAL.md §7.5 Leases, §12 Invoice 1 Timing [PASS-3:1F]
 * @decisions   D20 (FOR UPDATE on unit), spec §6 state machine
 * @session     S007
 */

require_once dirname(__DIR__, 3) . '/api/bootstrap.php';

require_method('POST');
require_auth_api();
require_permission('leases', 'edit');

$body = json_body();
$id   = clean_int($body['id'] ?? null);

if (!$id) {
    json_error('MISSING_REQUIRED', 'id is required.', 422);
}

$result = null;

db_transaction(function () use ($id, &$result) {
    // ── Fetch lease (D20: FOR UPDATE on the lease row) ─────────
    // S-MILEAGE-2A (D-A): also pull precharge_enabled/_amount/_balance
    // because the precharge_balance init below decides off them. The
    // FOR UPDATE here is the X-lock that prevents a concurrent writer
    // (manual SQL, admin tool) from changing precharge_* between this
    // read and our UPDATE below. The unit also gets FOR UPDATE further
    // down — both row locks are inside the same db_transaction so they
    // release atomically on commit.
    $lease = db_row(
        "SELECT id, status, contract_number, company_name_snapshot,
                customer_id, equipment_unit_id, start_date, billing_cycle,
                advance_billing_periods,
                unit_number_snapshot, last_billed_date,
                precharge_enabled, precharge_amount, precharge_balance,
                updated_at
         FROM leases WHERE id = ? AND deleted_at IS NULL
         FOR UPDATE",
        [$id]
    );

    if (!$lease) {
        json_error('NOT_FOUND', 'Lease not found.', 404);
    }

    // ── State machine validation ───────────────────────────────
    if ($lease['status'] !== 'pending') {
        json_error('INVALID_TRANSITION',
            "Cannot activate lease {$lease['contract_number']}: current status is '{$lease['status']}'. Only pending leases can be activated.", 409);
    }

    // ── D20: FOR UPDATE lock on the unit ───────────────────────
    // Re-validate availability at lock time — unit may have changed since lease was created
    $unit = db_row(
        "SELECT id, unit_number, status
         FROM equipment_units
         WHERE id = ? AND deleted_at IS NULL
         FOR UPDATE",
        [$lease['equipment_unit_id']]
    );

    if (!$unit) {
        json_error('NOT_FOUND', 'Equipment unit not found.', 404);
    }

    // After FIX #16, lease create reserves the unit (available → reserved).
    // Activate expects reserved status — on_lease/maintenance/etc means conflict.
    if ($unit['status'] !== 'reserved') {
        json_error('UNIT_UNAVAILABLE',
            "Cannot activate: unit {$unit['unit_number']} is not in reserved status (status: {$unit['status']}).", 409);
    }

    // ── S-LEASE-MILEAGE: capture starting odometer ─────────────
    // Path B: read-only Samsara fetch — never call any write endpoint.
    // Capture is non-blocking — if Samsara is unreachable / unit is not
    // linked / reading is implausible, we activate anyway with starting
    // odometer NULL and the lease detail page surfaces a manual-entry
    // banner. Stale (>24h) GPS readings still get persisted but flag a
    // manager warning via audit_log so the bookkeeper can recapture
    // before the first invoice generates.
    $odoCapture = (new \FleetForge\GPS\OdometerService())
        ->captureCurrentReading((int) $lease['equipment_unit_id']);

    $startKm        = null;
    $startSource    = null;
    $startFetchedAt = null;
    if ($odoCapture['success']) {
        $startKm        = $odoCapture['odometer_km'];
        $startSource    = 'gps';
        $startFetchedAt = $odoCapture['fetched_at'];
    }

    // ── Update lease status → active ───────────────────────────
    // next_billing_date: first day of next month after start_date
    // Only set for monthly billing cycle — on_close_only has no auto-billing schedule
    // Advance billing path overrides next_billing_date later in generateAdvanceBatch().
    $advancePeriods = (int) ($lease['advance_billing_periods'] ?? 0);
    $isAdvancePath  = ($advancePeriods > 0 && $lease['billing_cycle'] === 'monthly');

    $nextBillingDate = null;
    if ($lease['billing_cycle'] === 'monthly' && !$isAdvancePath) {
        $startTs         = strtotime($lease['start_date']);
        $nextBillingDate = date('Y-m-01', strtotime('+1 month', $startTs));
    }

    // Update lease — set odometer fields when capture succeeded; leave
    // them NULL when it didn't, so the manual-entry banner triggers on
    // the lease detail page. Existing odometer_start_km values (e.g. set
    // pre-activation via update_odometer.php) are preserved on capture
    // failure: COALESCE keeps the prior value rather than overwriting
    // with NULL.
    db_execute(
        "UPDATE leases
            SET status = 'active',
                next_billing_date = ?,
                odometer_start_km         = COALESCE(?, odometer_start_km),
                odometer_start_source     = COALESCE(?, odometer_start_source),
                odometer_start_fetched_at = COALESCE(?, odometer_start_fetched_at),
                updated_by = ?
          WHERE id = ?",
        [$nextBillingDate, $startKm, $startSource, $startFetchedAt, current_user_id(), $id]
    );

    // ── Update equipment_unit status → on_lease ────────────────
    db_execute(
        "UPDATE equipment_units SET status = 'on_lease', updated_by = ? WHERE id = ?",
        [current_user_id(), $lease['equipment_unit_id']]
    );

    // ── equipment_status_log ───────────────────────────────────
    $user      = current_user();
    $changedBy = $user['name'] ?? 'system';

    db_insert('equipment_status_log', [
        'equipment_unit_id' => $lease['equipment_unit_id'],
        'old_status'        => 'reserved',  // unit was reserved on lease create (FIX #16)
        'new_status'        => 'on_lease',
        'reason'            => "Lease {$lease['contract_number']} activated",
        'changed_by'        => $changedBy,
        'changed_by_user_id' => current_user_id(),
    ]);

    // ── lease_status_log ───────────────────────────────────────
    db_insert('lease_status_log', [
        'lease_id'   => $id,
        'old_status' => 'pending',
        'new_status' => 'active',
        'notes'      => 'Lease activated',
        'changed_by' => $changedBy,
        'user_id'    => current_user_id(),
    ]);

    // ── audit_log ──────────────────────────────────────────────
    // Annotate the activation entry with odometer-capture outcome so
    // managers can see at a glance whether a GPS fetch landed cleanly,
    // came in stale (>24h), or fell back to manual.
    $odoNote = '';
    if ($odoCapture['success']) {
        $odoNote = $odoCapture['is_stale']
            ? sprintf(' — odometer captured %.2f km (GPS, STALE: %d hours old, manager review recommended)',
                $odoCapture['odometer_km'],
                (int) round(($odoCapture['reading_age_seconds'] ?? 0) / 3600))
            : sprintf(' — odometer captured %.2f km (GPS)', $odoCapture['odometer_km']);
    } else {
        $odoNote = ' — odometer NOT captured (' . ($odoCapture['error'] ?? 'unknown') . '); manual entry required';
    }

    db_insert('audit_log', [
        'user_id'      => current_user_id(),
        'user_name'    => $changedBy,
        'action'       => 'status_change',
        'module'       => 'leases',
        'entity_type'  => 'lease',
        'entity_id'    => $id,
        'entity_label' => $lease['contract_number'],
        'notes'        => "Lease {$lease['contract_number']} activated — unit {$unit['unit_number']} → on_lease" . $odoNote,
        'old_values'   => json_encode(['status' => 'pending']),
        'new_values'   => json_encode([
            'status'                => 'active',
            'odometer_start_km'     => $startKm,
            'odometer_start_source' => $startSource,
            'odometer_start_is_stale' => $odoCapture['is_stale'],
        ]),
        'ip_address'   => $_SERVER['REMOTE_ADDR'] ?? '127.0.0.1',
    ]);

    // ── S-MILEAGE-2A (D-A): precharge_balance initialization ───
    // On lease activation, initialize the running drawdown balance to
    // the user-set precharge_amount when the lease opted into Model B
    // precharge billing. Idempotent by WHERE-clause guard
    // (precharge_balance IS NULL) so a re-run on a lease whose balance
    // was already set never double-inits — the state machine at the top
    // of this transaction prevents real re-activation, but the guard is
    // defense in depth against a manual-SQL or admin-tool race.
    // The lease row was FOR UPDATE-locked at the SELECT above (D20) so
    // no concurrent writer can mutate precharge_* between read + write.
    // chk_leases_precharge_amount CHECK at the DB layer guarantees
    // precharge_amount > 0 whenever precharge_enabled = 1; the PHP
    // guard mirrors the rule so we never fire on a malformed row.
    // Lifecycle: S-MILEAGE-2B decrements precharge_balance per invoice;
    // S-MILEAGE-3 surfaces refund picker when close-time balance > 0.
    if ((int) ($lease['precharge_enabled'] ?? 0) === 1
        && $lease['precharge_amount'] !== null
        && $lease['precharge_balance'] === null) {
        $prechargeInitRows = db_execute(
            "UPDATE leases
                SET precharge_balance = precharge_amount,
                    updated_at = NOW(),
                    updated_by = ?
              WHERE id = ?
                AND precharge_enabled = 1
                AND precharge_amount IS NOT NULL
                AND precharge_balance IS NULL",
            [current_user_id(), $id]
        );

        if ($prechargeInitRows === 1) {
            $prechargeAmt = (string) $lease['precharge_amount'];
            db_insert('audit_log', [
                'user_id'      => current_user_id(),
                'user_name'    => $changedBy,
                'action'       => 'update',
                'module'       => 'leases',
                'entity_type'  => 'lease_precharge_balance_init',
                'entity_id'    => $id,
                'entity_label' => $lease['contract_number'],
                'notes'        => "Lease {$lease['contract_number']} precharge balance initialized to \${$prechargeAmt} on activation (S-MILEAGE-2A D-A).",
                'old_values'   => json_encode([
                    'precharge_balance' => null,
                ]),
                'new_values'   => json_encode([
                    'precharge_amount'  => $prechargeAmt,
                    'precharge_balance' => $prechargeAmt,
                ]),
                'ip_address'   => $_SERVER['REMOTE_ADDR'] ?? '127.0.0.1',
            ]);
        }
    }

    // ── FIX #17 / ADV-BILL-1: Generate Invoice(s) on activation ────
    // Legacy path: single Invoice 1 (period start_date → end of start month).
    // Advance path (ADV-BILL-1): N+1 invoices (Invoice 1 + N future-period invoices)
    // generated by InvoiceGenerator::generateAdvanceBatch(). The batch advances
    // lease.next_billing_date past the final advance period so the monthly cron
    // skips that range automatically.
    //
    // db_transaction() nesting is safe — InvoiceGenerator calls db_transaction()
    // too, but the nesting guard in db.php means it runs in this outer transaction.
    $generator = new \FleetForge\Billing\InvoiceGenerator();

    // S-LEASE-MILEAGE: surface odometer-capture outcome on the response
    // so the UI can react (toast for stale GPS, banner for unavailable).
    $odoBlock = [
        'captured'           => $odoCapture['success'],
        'odometer_km'        => $odoCapture['odometer_km'],
        'source'             => $odoCapture['source'],
        'is_stale'           => $odoCapture['is_stale'],
        'reading_age_seconds'=> $odoCapture['reading_age_seconds'],
        'error'              => $odoCapture['error'],
    ];

    if ($isAdvancePath) {
        // ADV-BILL-1: N+1 invoice batch. All share invoice_date / tax / FX / markup.
        $batch = $generator->generateAdvanceBatch($id, current_user_id());
        $result = [
            'id'           => $id,
            'status'       => 'active',
            'invoice_ids'  => array_column($batch['invoices'], 'invoice_id'),
            'odometer'     => $odoBlock,
            'advance'      => [
                'total_count'        => $batch['total_count'],
                'first_period_start' => $batch['first_period_start'],
                'last_period_end'    => $batch['last_period_end'],
                'batch_total_amount' => $batch['batch_total_amount'],
                'next_billing_date'  => $batch['next_billing_date'],
            ],
        ];
    } else {
        // Legacy path: single Invoice 1.
        // Period: start_date → last day of that month.
        // billing_type='full_month' if start is the 1st, else 'partial_start' (pro-rate).
        $startDate       = $lease['start_date'];
        $lastDayOfMonth  = date('Y-m-t', strtotime($startDate));
        $firstDayOfMonth = date('Y-m-01', strtotime($startDate));
        $billingType     = ($startDate === $firstDayOfMonth) ? 'full_month' : 'partial_start';

        $invoiceResult = $generator->createFromLease([
            'lease_id'          => $id,
            'period_start'      => $startDate,
            'period_end'        => $lastDayOfMonth,
            'billing_type'      => $billingType,
            'invoice_type'      => 'regular',
            'created_by'        => current_user_id(),
            'auto_generated'    => 1,
            'generation_source' => 'manual',  // ENUM: cron|manual|lease_close|late_fee_cron|advance
            // S-LEASE-MILEAGE: anchor Invoice 1 to the just-captured starting
            // odometer so the period_start column on the first invoice matches
            // lease.odometer_start_km. period_end is unknown at activation —
            // the next month's cron run computes period_distance for the next
            // invoice using either prev.odometer_at_period_end_km or this
            // lease.odometer_start_km as the anchor.
            'odometer_at_period_start_km' => $startKm,
            'odometer_source'             => $startSource,
            'odometer_fetched_at'         => $startFetchedAt,
        ]);

        $result = [
            'id'         => $id,
            'status'     => 'active',
            'invoice_id' => $invoiceResult['invoice_id'],
            'odometer'   => $odoBlock,
        ];
    }

    // ── In-app notifications (NOTIF-1 + ADV-BILL-1 D-D) ────────
    // Staff: lease.activated. Customer portal: lease.activated PLUS, when the
    // advance path ran, a single batched invoice notification covering all
    // pre-paid future periods (D-D).
    try {
        $unitNumber = $unit['unit_number'] ?? ($lease['unit_number_snapshot'] ?? '');
        \FleetForge\Notifications\NotificationService::notify(
            type:       'lease.activated',
            title:      "Lease {$lease['contract_number']} activated",
            message:    "Lease {$lease['contract_number']} activated — unit {$unitNumber} is now on lease",
            entityType: 'lease',
            entityId:   $id,
            url:        '/fleetforge/leases/show?id=' . $id
        );

        // Portal notification: only if we know the customer_id
        if (!empty($lease['customer_id'])) {
            \FleetForge\Notifications\NotificationService::notifyPortal(
                type:       'lease.activated',
                customerId: (int) $lease['customer_id'],
                title:      "Your lease is now active",
                message:    "Lease {$lease['contract_number']} is now active.",
                entityType: 'lease',
                entityId:   $id,
                url:        '/fleetforge/portal/leases/show?id=' . $id
            );

            // D-D: single batched portal notification for the advance batch.
            if ($isAdvancePath && !empty($result['advance'])) {
                $adv      = $result['advance'];
                $totalFmt = number_format((float) $adv['batch_total_amount'], 2, '.', ',');
                \FleetForge\Notifications\NotificationService::notifyPortal(
                    type:       'invoice.created',
                    customerId: (int) $lease['customer_id'],
                    title:      "{$adv['total_count']} new invoices for upcoming billing periods",
                    message:    "Total of \${$totalFmt} across periods {$adv['first_period_start']} – {$adv['last_period_end']}.",
                    entityType: 'lease',
                    entityId:   $id,
                    url:        '/fleetforge/portal/leases/show?id=' . $id
                );
            }
        }
    } catch (\Throwable $e) {
        error_log('[NOTIF lease.activated] ' . $e->getMessage());
    }
});

json_success($result);
