<?php
declare(strict_types=1);

/**
 * FleetForge — Lease Activate API
 *
 * @file        api/v1/leases/activate.php
 * @description Transitions a lease from 'pending' → 'active'.
 *
 *              State machine (spec §6):
 *                pending → active (this endpoint)
 *                active → completed | cancelled
 *
 *              Concurrency (D20): acquires FOR UPDATE lock on equipment_unit.
 *              Re-validates unit status at lock time — prevents race where unit
 *              was leased between create and activate.
 *
 *              On activation:
 *              1. Validate lease is pending
 *              2. FOR UPDATE lock on unit — check still available
 *              3. Update lease status → 'active'
 *              4. Update equipment_unit status → 'on_lease'
 *              5. Write equipment_status_log entry
 *              6. Write lease_status_log entry
 *              7. Write audit_log entry
 *
 *              Invoice 1 will be generated by InvoiceGenerator (not yet built — S009+).
 *              This endpoint stubs the trigger point with a comment.
 *
 * @method      POST
 * @body        JSON — id (lease id, required)
 * @auth        Session required; require_permission('leases','edit')
 * @returns     200 { id, status } | 409 INVALID_TRANSITION | 409 UNIT_UNAVAILABLE | 404 NOT_FOUND
 *
 * @depends     api/bootstrap.php
 * @spec        FLEETFORGE_SPEC_FINAL.md §7.5 Leases, §12 Invoice 1 Timing [PASS-3:1F]
 * @decisions   D20 (FOR UPDATE on unit), spec §6 state machine
 * @session     S007
 */

require_once dirname(__DIR__, 3) . '/api/bootstrap.php';

require_method('POST');
require_auth_api();
require_permission('leases', 'edit');

$body = json_body();
$id   = clean_int($body['id'] ?? null);

if (!$id) {
    json_error('MISSING_REQUIRED', 'id is required.', 422);
}

$result = null;

db_transaction(function () use ($id, &$result) {
    // ── Fetch lease ────────────────────────────────────────────
    $lease = db_row(
        "SELECT id, status, contract_number, company_name_snapshot,
                equipment_unit_id, start_date, billing_cycle, unit_number_snapshot,
                last_billed_date
         FROM leases WHERE id = ? AND deleted_at IS NULL",
        [$id]
    );

    if (!$lease) {
        json_error('NOT_FOUND', 'Lease not found.', 404);
    }

    // ── State machine validation ───────────────────────────────
    if ($lease['status'] !== 'pending') {
        json_error('INVALID_TRANSITION',
            "Cannot activate lease {$lease['contract_number']}: current status is '{$lease['status']}'. Only pending leases can be activated.", 409);
    }

    // ── D20: FOR UPDATE lock on the unit ───────────────────────
    // Re-validate availability at lock time — unit may have changed since lease was created
    $unit = db_row(
        "SELECT id, unit_number, status
         FROM equipment_units
         WHERE id = ? AND deleted_at IS NULL
         FOR UPDATE",
        [$lease['equipment_unit_id']]
    );

    if (!$unit) {
        json_error('NOT_FOUND', 'Equipment unit not found.', 404);
    }

    // After FIX #16, lease create reserves the unit (available → reserved).
    // Activate expects reserved status — on_lease/maintenance/etc means conflict.
    if ($unit['status'] !== 'reserved') {
        json_error('UNIT_UNAVAILABLE',
            "Cannot activate: unit {$unit['unit_number']} is not in reserved status (status: {$unit['status']}).", 409);
    }

    // ── Update lease status → active ───────────────────────────
    // next_billing_date: first day of next month after start_date
    // Only set for monthly billing cycle — on_close_only has no auto-billing schedule
    $nextBillingDate = null;
    if ($lease['billing_cycle'] === 'monthly') {
        $startTs         = strtotime($lease['start_date']);
        $nextBillingDate = date('Y-m-01', strtotime('+1 month', $startTs));
    }

    db_execute(
        "UPDATE leases SET status = 'active', next_billing_date = ?, updated_by = ? WHERE id = ?",
        [$nextBillingDate, current_user_id(), $id]
    );

    // ── Update equipment_unit status → on_lease ────────────────
    db_execute(
        "UPDATE equipment_units SET status = 'on_lease', updated_by = ? WHERE id = ?",
        [current_user_id(), $lease['equipment_unit_id']]
    );

    // ── equipment_status_log ───────────────────────────────────
    $user      = current_user();
    $changedBy = $user['name'] ?? 'system';

    db_insert('equipment_status_log', [
        'equipment_unit_id' => $lease['equipment_unit_id'],
        'old_status'        => 'reserved',  // unit was reserved on lease create (FIX #16)
        'new_status'        => 'on_lease',
        'reason'            => "Lease {$lease['contract_number']} activated",
        'changed_by'        => $changedBy,
        'changed_by_user_id' => current_user_id(),
    ]);

    // ── lease_status_log ───────────────────────────────────────
    db_insert('lease_status_log', [
        'lease_id'   => $id,
        'old_status' => 'pending',
        'new_status' => 'active',
        'notes'      => 'Lease activated',
        'changed_by' => $changedBy,
        'user_id'    => current_user_id(),
    ]);

    // ── audit_log ──────────────────────────────────────────────
    db_insert('audit_log', [
        'user_id'      => current_user_id(),
        'user_name'    => $changedBy,
        'action'       => 'status_change',
        'module'       => 'leases',
        'entity_type'  => 'lease',
        'entity_id'    => $id,
        'entity_label' => $lease['contract_number'],
        'notes'        => "Lease {$lease['contract_number']} activated — unit {$unit['unit_number']} → on_lease",
        'old_values'   => json_encode(['status' => 'pending']),
        'new_values'   => json_encode(['status' => 'active']),
        'ip_address'   => $_SERVER['REMOTE_ADDR'] ?? '127.0.0.1',
    ]);

    // ── FIX #17: Generate Invoice 1 on activation ─────────────
    // Per spec §12 [PASS-3:1F]: Invoice 1 created at activation time, not lease creation.
    // Period: start_date → last day of that month.
    // billing_type='full_month' if start is the 1st, else 'partial_start' (pro-rate).
    // db_transaction() nesting is safe — InvoiceGenerator calls db_transaction() too,
    // but the nesting guard in db.php means it runs in this outer transaction.
    $startDate       = $lease['start_date'];
    $lastDayOfMonth  = date('Y-m-t', strtotime($startDate));
    $firstDayOfMonth = date('Y-m-01', strtotime($startDate));
    $billingType     = ($startDate === $firstDayOfMonth) ? 'full_month' : 'partial_start';

    $generator     = new \FleetForge\Billing\InvoiceGenerator();
    $invoiceResult = $generator->createFromLease([
        'lease_id'          => $id,
        'period_start'      => $startDate,
        'period_end'        => $lastDayOfMonth,
        'billing_type'      => $billingType,
        'invoice_type'      => 'regular',
        'created_by'        => current_user_id(),
        'auto_generated'    => 1,
        'generation_source' => 'manual',  // ENUM: cron|manual|lease_close|late_fee_cron
    ]);

    $result = ['id' => $id, 'status' => 'active', 'invoice_id' => $invoiceResult['invoice_id']];
});

json_success($result);
